apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: snowplane-mutating-webhooks
webhooks:
  - name: mutate-database.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    reinvocationPolicy: Never
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /mutate-snowplane-v1alpha1-database
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["databases"]
    matchPolicy: Equivalent
  - name: mutate-schema.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    reinvocationPolicy: Never
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /mutate-snowplane-v1alpha1-schema
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["schemas"]
    matchPolicy: Equivalent
  - name: mutate-warehouse.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    reinvocationPolicy: Never
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /mutate-snowplane-v1alpha1-warehouse
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["warehouses"]
    matchPolicy: Equivalent
  - name: mutate-accountrole.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    reinvocationPolicy: Never
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /mutate-snowplane-v1alpha1-accountrole
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["accountroles"]
    matchPolicy: Equivalent
  - name: mutate-databaserole.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    reinvocationPolicy: Never
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /mutate-snowplane-v1alpha1-databaserole
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["databaseroles"]
    matchPolicy: Equivalent
  - name: mutate-grant.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    reinvocationPolicy: Never
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /mutate-snowplane-v1alpha1-grant
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["grants"]
    matchPolicy: Equivalent
  - name: mutate-user.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    reinvocationPolicy: Never
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /mutate-snowplane-v1alpha1-user
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["users"]
    matchPolicy: Equivalent
  - name: mutate-table.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    reinvocationPolicy: Never
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /mutate-snowplane-v1alpha1-table
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["tables"]
    matchPolicy: Equivalent
  - name: mutate-view.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    reinvocationPolicy: Never
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /mutate-snowplane-v1alpha1-view
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["views"]
    matchPolicy: Equivalent
  - name: mutate-stage.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    reinvocationPolicy: Never
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /mutate-snowplane-v1alpha1-stage
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["stages"]
    matchPolicy: Equivalent
  - name: mutate-providerconfig.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    reinvocationPolicy: Never
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /mutate-snowplane-v1alpha1-providerconfig
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["providerconfigs"]
    matchPolicy: Equivalent
