apiVersion: v1
kind: Service
metadata:
  name: snowplane-webhook-service
  namespace: snowplane-system
  labels:
    app.kubernetes.io/name: snowplane
    app.kubernetes.io/component: webhook
spec:
  selector:
    app.kubernetes.io/name: snowplane
    app.kubernetes.io/component: controller-manager
  ports:
    - name: https
      port: 443
      targetPort: 9443
      protocol: TCP
