apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: snowplane-validating-webhooks
webhooks:
  - name: validate-database.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /validate-snowplane-v1alpha1-database
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["databases"]
    matchPolicy: Equivalent
  - name: validate-schema.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /validate-snowplane-v1alpha1-schema
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["schemas"]
    matchPolicy: Equivalent
  - name: validate-warehouse.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /validate-snowplane-v1alpha1-warehouse
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["warehouses"]
    matchPolicy: Equivalent
  - name: validate-accountrole.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /validate-snowplane-v1alpha1-accountrole
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["accountroles"]
    matchPolicy: Equivalent
  - name: validate-databaserole.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /validate-snowplane-v1alpha1-databaserole
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["databaseroles"]
    matchPolicy: Equivalent
  - name: validate-grant.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /validate-snowplane-v1alpha1-grant
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["grants"]
    matchPolicy: Equivalent
  - name: validate-user.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /validate-snowplane-v1alpha1-user
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["users"]
    matchPolicy: Equivalent
  - name: validate-table.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /validate-snowplane-v1alpha1-table
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["tables"]
    matchPolicy: Equivalent
  - name: validate-view.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /validate-snowplane-v1alpha1-view
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["views"]
    matchPolicy: Equivalent
  - name: validate-stage.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /validate-snowplane-v1alpha1-stage
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["stages"]
    matchPolicy: Equivalent
  - name: validate-providerconfig.snowplane.hupe1980.github.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: snowplane-webhook-service
        namespace: snowplane-system
        path: /validate-snowplane-v1alpha1-providerconfig
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["snowplane.hupe1980.github.io"]
        apiVersions: ["v1alpha1"]
        resources: ["providerconfigs"]
    matchPolicy: Equivalent
