---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snowplane-viewer
  labels:
    app.kubernetes.io/name: snowplane
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - snowplane.hupe1980.github.io
  resources:
  - databases
  - schemas
  - warehouses
  - accountroles
  - databaseroles
  - grantprivilegestoaccountroles
  - grantprivilegestodatabaseroles
  - grantprivilegestoshares
  - grantownerships
  - users
  - tables
  - views
  - stages
  - tasks
  - tags
  - tagassociations
  - networkpolicyattachments
  - passwordpolicyattachments
  - maskingpolicyapplications
  - tableconstraints
  - networkpolicies
  - resourcemonitors
  - maskingpolicies
  - rowaccesspolicies
  - dynamictables
  - fileformats
  - sequences
  - externaltables
  - materializedviews
  - pipes
  - storageintegrations
  - securityintegrations
  - saml2integrations
  - externaloauthintegrations
  - apiintegrations
  - secondarydatabases
  - shareddatabases
  - failovergroups
  - passwordpolicies
  - authenticationpolicies
  - networkrules
  - alerts
  - notificationintegrations
  - accountroleassignments
  - databaseroleassignments
  - streamontables
  - streamonviews
  - streamonexternaltables
  - streamondirectorytables
  - streamondynamictables
  - fieldexports
  - providerconfigs
  - proceduresqls
  - procedurejavascripts
  - procedurepythons
  - procedurejavas
  - procedurescalas
  - functionsqls
  - functionjavascripts
  - functionpythons
  - functionjavas
  - functionscalas
  - sqlstatements
  - secretwithclientcredentials
  - secretwithauthorizationcodegrants
  - secretwithbasicauthentications
  - secretwithgenericstrings
  - apiauthenticationintegrationwithclientcredentials
  - apiauthenticationintegrationwithauthorizationcodegrants
  - apiauthenticationintegrationwithjwtbearers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snowplane.hupe1980.github.io
  resources:
  - databases/status
  - schemas/status
  - warehouses/status
  - accountroles/status
  - databaseroles/status
  - grantprivilegestoaccountroles/status
  - grantprivilegestodatabaseroles/status
  - grantprivilegestoshares/status
  - grantownerships/status
  - users/status
  - tables/status
  - views/status
  - stages/status
  - tasks/status
  - tags/status
  - tagassociations/status
  - networkpolicyattachments/status
  - passwordpolicyattachments/status
  - maskingpolicyapplications/status
  - tableconstraints/status
  - networkpolicies/status
  - resourcemonitors/status
  - maskingpolicies/status
  - rowaccesspolicies/status
  - dynamictables/status
  - fileformats/status
  - sequences/status
  - externaltables/status
  - materializedviews/status
  - pipes/status
  - storageintegrations/status
  - securityintegrations/status
  - saml2integrations/status
  - externaloauthintegrations/status
  - apiintegrations/status
  - secondarydatabases/status
  - shareddatabases/status
  - failovergroups/status
  - passwordpolicies/status
  - authenticationpolicies/status
  - networkrules/status
  - alerts/status
  - notificationintegrations/status
  - accountroleassignments/status
  - databaseroleassignments/status
  - streamontables/status
  - streamonviews/status
  - streamonexternaltables/status
  - streamondirectorytables/status
  - streamondynamictables/status
  - fieldexports/status
  - providerconfigs/status
  - proceduresqls/status
  - procedurejavascripts/status
  - procedurepythons/status
  - procedurejavas/status
  - procedurescalas/status
  - functionsqls/status
  - functionjavascripts/status
  - functionpythons/status
  - functionjavas/status
  - functionscalas/status
  - sqlstatements/status
  - secretwithclientcredentials/status
  - secretwithauthorizationcodegrants/status
  - secretwithbasicauthentications/status
  - secretwithgenericstrings/status
  - apiauthenticationintegrationwithclientcredentials/status
  - apiauthenticationintegrationwithauthorizationcodegrants/status
  - apiauthenticationintegrationwithjwtbearers/status
  verbs:
  - get
