---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snowplane-viewer
  labels:
    app.kubernetes.io/name: snowplane
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - snowplane.hupe1980.github.io
  resources:
  - databases
  - schemas
  - warehouses
  - accountroles
  - databaseroles
  - accountrolegrants
  - databaserolegrants
  - sharegrants
  - grantownerships
  - users
  - tables
  - views
  - stages
  - tasks
  - streams
  - tags
  - networkpolicies
  - resourcemonitors
  - maskingpolicies
  - rowaccesspolicies
  - dynamictables
  - fileformats
  - pipes
  - storageintegrations
  - fieldexports
  - providerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snowplane.hupe1980.github.io
  resources:
  - databases/status
  - schemas/status
  - warehouses/status
  - accountroles/status
  - databaseroles/status
  - accountrolegrants/status
  - databaserolegrants/status
  - sharegrants/status
  - grantownerships/status
  - users/status
  - tables/status
  - views/status
  - stages/status
  - tasks/status
  - streams/status
  - tags/status
  - networkpolicies/status
  - resourcemonitors/status
  - maskingpolicies/status
  - rowaccesspolicies/status
  - dynamictables/status
  - fileformats/status
  - pipes/status
  - storageintegrations/status
  - fieldexports/status
  - providerconfigs/status
  verbs:
  - get
