#!/usr/bin/env bash
# setup-integration-test.sh — Bootstrap a Snowflake test account for Snowplane integration tests.
#
# What this script does:
#   1. Generates an RSA 2048-bit key pair (unencrypted PKCS#8 private key)
#   2. Creates a SQL file to run in your Snowflake account (creates role, user, grants)
#   3. Creates a .env file with all variables needed by the integration test suite
#
# Usage:
#   ./hack/setup-integration-test.sh \
#       --account <orgname-accountname> \
#       [--test-user SNOWPLANE_TEST_USER] \
#       [--test-role SNOWPLANE_TEST_ROLE] \
#       [--out-dir .]
#
# After running:
#   1. Execute the generated SQL in Snowflake as ACCOUNTADMIN:
#      snowsql -a <account> -f snowplane_test_setup.sql
#   2. Source the .env:  source .env
#   3. Run integration tests:  SNOWFLAKE_INTEGRATION=true go test ./...

set -euo pipefail

# ─── Defaults ────────────────────────────────────────────────────────────────
SNOWFLAKE_ACCOUNT=""
TEST_USER="SNOWPLANE_TEST_USER"
TEST_ROLE="SNOWPLANE_TEST_ROLE"
OUT_DIR="."

# ─── Parse arguments ────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --account)     SNOWFLAKE_ACCOUNT="$2"; shift 2 ;;
    --test-user)   TEST_USER="$2"; shift 2 ;;
    --test-role)   TEST_ROLE="$2"; shift 2 ;;
    --out-dir)     OUT_DIR="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,/^$/p' "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$SNOWFLAKE_ACCOUNT" ]]; then
  echo "Error: --account is required (e.g. --account orgname-accountname)" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

KEY_DIR="${OUT_DIR}/keys"
PRIVATE_KEY_FILE="${KEY_DIR}/snowplane_test_rsa_key.p8"
PUBLIC_KEY_FILE="${KEY_DIR}/snowplane_test_rsa_key.pub"
SQL_FILE="${OUT_DIR}/snowplane_test_setup.sql"
ENV_FILE="${OUT_DIR}/.env"

# ─── Step 1: Generate RSA key pair ──────────────────────────────────────────
echo "==> Generating RSA 2048-bit key pair..."
mkdir -p "$KEY_DIR"

# Generate unencrypted PKCS#8 private key (required by Snowflake Go driver)
openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "$PRIVATE_KEY_FILE" 2>/dev/null
chmod 600 "$PRIVATE_KEY_FILE"

# Extract public key in PEM format
openssl pkey -in "$PRIVATE_KEY_FILE" -pubout -out "$PUBLIC_KEY_FILE" 2>/dev/null

echo "    Private key: ${PRIVATE_KEY_FILE}"
echo "    Public key:  ${PUBLIC_KEY_FILE}"

# Extract the raw public key body (strip header/footer, join lines) for Snowflake SQL
PUBLIC_KEY_BODY=$(grep -v "^-----" "$PUBLIC_KEY_FILE" | tr -d '\n')

# ─── Step 2: Generate SQL setup file ────────────────────────────────────────
echo "==> Generating SQL setup file: ${SQL_FILE}"

cat > "$SQL_FILE" <<EOSQL
-- =============================================================================
-- Snowplane Integration Test Account Setup
-- Generated by: hack/setup-integration-test.sh
-- Date: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
--
-- Run this file as an ACCOUNTADMIN user:
--   snowsql -a ${SNOWFLAKE_ACCOUNT} -f ${SQL_FILE}
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- 1. Create a dedicated role for integration tests
CREATE ROLE IF NOT EXISTS ${TEST_ROLE}
  COMMENT = 'Role for Snowplane integration tests';

-- 2. Grant necessary privileges to the test role
--    The operator needs to manage databases, schemas, warehouses, users, roles, grants
GRANT CREATE DATABASE   ON ACCOUNT TO ROLE ${TEST_ROLE};
GRANT CREATE WAREHOUSE  ON ACCOUNT TO ROLE ${TEST_ROLE};
GRANT CREATE ROLE       ON ACCOUNT TO ROLE ${TEST_ROLE};
GRANT CREATE USER       ON ACCOUNT TO ROLE ${TEST_ROLE};
GRANT MANAGE GRANTS     ON ACCOUNT TO ROLE ${TEST_ROLE};

-- 4. Create the test user with key pair authentication
CREATE USER IF NOT EXISTS ${TEST_USER}
  RSA_PUBLIC_KEY = '${PUBLIC_KEY_BODY}'
  DEFAULT_ROLE = '${TEST_ROLE}'
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'Service user for Snowplane integration tests';

-- 5. Grant the test role to the test user
GRANT ROLE ${TEST_ROLE} TO USER ${TEST_USER};

-- 6. Verify setup
SHOW USERS LIKE '${TEST_USER}';
SHOW GRANTS TO USER ${TEST_USER};

-- =============================================================================
-- Teardown (run manually when done with testing):
--
--   USE ROLE ACCOUNTADMIN;
--   DROP USER IF EXISTS ${TEST_USER};
--   DROP ROLE IF EXISTS ${TEST_ROLE};
-- =============================================================================
EOSQL

# ─── Step 3: Generate .env file ─────────────────────────────────────────────
echo "==> Generating .env file: ${ENV_FILE}"

# Read private key contents for the .env (escape newlines for shell sourcing)
PRIVATE_KEY_CONTENT=$(cat "$PRIVATE_KEY_FILE")

cat > "$ENV_FILE" <<EOENV
# Snowplane Integration Test Environment
# Generated by: hack/setup-integration-test.sh
# Date: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
#
# Usage: source .env && SNOWFLAKE_INTEGRATION=true go test ./...

# Enable integration tests
export SNOWFLAKE_INTEGRATION=true

# Snowflake connection
export SNOWFLAKE_ACCOUNT="${SNOWFLAKE_ACCOUNT}"
export SNOWFLAKE_USER="${TEST_USER}"
export SNOWFLAKE_ROLE="${TEST_ROLE}"

# Key pair authentication — PEM-encoded private key
export SNOWFLAKE_PRIVATE_KEY=$(printf '%q' "$PRIVATE_KEY_CONTENT")
EOENV

chmod 600 "$ENV_FILE"

# ─── Summary ────────────────────────────────────────────────────────────────
echo ""
echo "=== Setup complete ==="
echo ""
echo "Next steps:"
echo ""
echo "  1. Run the SQL in your Snowflake account as ACCOUNTADMIN:"
echo "     snowsql -a ${SNOWFLAKE_ACCOUNT} -f ${SQL_FILE}"
echo ""
echo "  2. Source the .env file:"
echo "     source ${ENV_FILE}"
echo ""
echo "  3. Run the integration tests:"
echo "     go test -tags integration ./..."
echo ""
echo "Files created:"
echo "  ${PRIVATE_KEY_FILE}   (keep secret — in .gitignore)"
echo "  ${PUBLIC_KEY_FILE}"
echo "  ${SQL_FILE}"
echo "  ${ENV_FILE}               (keep secret — in .gitignore)"
echo ""
echo "⚠  Add 'keys/' to .gitignore if not already present!"
