//go:build integration

// Package snowflake_test contains real (non-mock) integration tests that
// exercise the Snowflake client against a live Snowflake account.
//
// Prerequisites:
//
//	source .env   # generated by hack/setup-integration-test.sh
//	go test -tags integration -v -count=1 ./test/integration/snowflake/...
//
// The tests are skipped entirely when SNOWFLAKE_INTEGRATION != "true".
package snowflake_test

import (
	"context"
	"fmt"
	"math/rand/v2"
	"os"
	"testing"

	"github.com/hupe1980/snowplane/internal/clients/snowflake"
)

var (
	sfClient *snowflake.Client
	testCtx  = context.Background()
)

func TestMain(m *testing.M) {
	if os.Getenv("SNOWFLAKE_INTEGRATION") != "true" {
		fmt.Println("SKIP: set SNOWFLAKE_INTEGRATION=true to run real Snowflake tests")
		os.Exit(0)
	}

	client, err := snowflake.NewClient(snowflake.Config{
		Account:    os.Getenv("SNOWFLAKE_ACCOUNT"),
		User:       os.Getenv("SNOWFLAKE_USER"),
		Role:       os.Getenv("SNOWFLAKE_ROLE"),
		PrivateKey: os.Getenv("SNOWFLAKE_PRIVATE_KEY"),
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "FATAL: failed to create Snowflake client: %v\n", err)
		os.Exit(1)
	}

	if err := client.Ping(testCtx); err != nil {
		fmt.Fprintf(os.Stderr, "FATAL: Snowflake ping failed: %v\n", err)
		os.Exit(1)
	}

	sfClient = client

	code := m.Run()

	_ = sfClient.Close()
	os.Exit(code)
}

// uniqueName returns a test-unique Snowflake object name with the given prefix.
func uniqueName(prefix string) string {
	return fmt.Sprintf("SNOWPLANE_IT_%s_%d", prefix, rand.Int32N(900000)+100000) //nolint:gosec
}

func ptrString(s string) *string { return &s }
func ptrBool(b bool) *bool       { return &b }
func ptrInt32(i int32) *int32    { return &i }
