apiVersion: snowplane.hupe1980.github.io/v1alpha1
kind: DynamicTable
metadata:
  name: my-dynamic-table
spec:
  name: MY_DYNAMIC_TABLE
  providerRef:
    name: default
  databaseRef:
    name: my-database
  schemaRef:
    name: my-schema
  query: "SELECT * FROM MY_DATABASE.MY_SCHEMA.MY_SOURCE_TABLE"
  targetLag: "1 hour"
  warehouseRef:
    name: my-warehouse
  comment: "Dynamic table managed by Snowplane"
