apiVersion: snowplane.hupe1980.github.io/v1alpha1
kind: GrantPrivilegesToDatabaseRole
metadata:
  name: usage-to-dbrole
  namespace: default
spec:
  privilege: USAGE
  on:
    database: MY_DB
  databaseRole: '"MY_DB"."DATA_ANALYST"'
  providerRef:
    name: default
