apiVersion: snowplane.hupe1980.github.io/v1alpha1
kind: GrantPrivilegesToShare
metadata:
  name: usage-to-share
  namespace: default
spec:
  privilege: USAGE
  on:
    database: MY_DB
  share: MY_SHARE
  providerRef:
    name: default
