apiVersion: snowplane.hupe1980.github.io/v1alpha1
kind: PasswordPolicyAttachment
metadata:
  name: user-password-policy
spec:
  providerRef:
    name: default
  # Use a PolicyRef to reference an existing PasswordPolicy CR instead of a raw name.
  policyRef:
    name: my-password-policy
  targetType: USER
  targetName: MY_USER
