apiVersion: snowplane.hupe1980.github.io/v1alpha1
kind: PasswordPolicyAttachment
metadata:
  name: account-password-policy
spec:
  providerRef:
    name: default
  policyName: '"MY_DB"."MY_SCHEMA"."MY_PASSWORD_POLICY"'
  targetType: ACCOUNT
