apiVersion: snowplane.hupe1980.github.io/v1alpha1
kind: PasswordPolicy
metadata:
  name: strict-password-policy
spec:
  providerRef:
    name: default
  name: STRICT_PASSWORD_POLICY
  databaseRef:
    name: my-database
  schemaRef:
    name: my-schema
  passwordMinLength: 12
  passwordMaxLength: 256
  passwordMinUpperCase: 2
  passwordMinLowerCase: 2
  passwordMinNumeric: 1
  passwordMinSpecial: 1
  passwordMaxAgeDays: 90
  passwordMaxRetries: 5
  passwordLockoutTimeMins: 30
  passwordHistory: 10
  comment: "Strict password policy managed by Snowplane"
