apiVersion: snowplane.hupe1980.github.io/v1alpha1
kind: SecurityIntegration
metadata:
  name: my-scim-integration
spec:
  providerRef:
    name: default
  name: MY_SCIM_INTEGRATION
  type: SCIM
  scimConfig:
    client: AZURE
    runAsRole: AAD_PROVISIONER
  enabled: true
  comment: "SCIM provisioning from Azure AD managed by Snowplane"
