apiVersion: snowplane.hupe1980.github.io/v1alpha1
kind: Stream
metadata:
  name: my-stream
spec:
  providerRef:
    name: default
  name: MY_STREAM
  databaseRef:
    name: my-database
  schemaRef:
    name: my-schema
  sourceType: TABLE
  sourceName: '"MY_DB"."MY_SCHEMA"."MY_TABLE"'
  comment: "Basic stream on a table"
