apiVersion: snowplane.hupe1980.github.io/v1alpha1
kind: StreamOnExternalTable
metadata:
  name: my-stream-on-external-table
spec:
  name: MY_STREAM_ON_EXTERNAL_TABLE
  providerRef:
    name: default
  databaseRef:
    name: my-database
  schemaRef:
    name: my-schema
  externalTableRef:
    name: my-external-table
  insertOnly: true
  comment: "Stream on external table managed by Snowplane"
