apiVersion: snowplane.hupe1980.github.io/v1alpha1
kind: StreamOnDirectoryTable
metadata:
  name: my-stream-on-directory-table
spec:
  name: MY_STREAM_ON_DIRECTORY_TABLE
  providerRef:
    name: default
  databaseRef:
    name: my-database
  schemaRef:
    name: my-schema
  stageRef:
    name: my-stage
  comment: "Stream on directory table managed by Snowplane"
