// Code generated by hack/gen-accessors/main.go; DO NOT EDIT.

package v1alpha1

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

// ---------------------------------------------------------------------------
// Database
// ---------------------------------------------------------------------------

func (d *Database) GetConditions() []metav1.Condition {
	return d.Status.Conditions
}

func (d *Database) SetConditions(conditions []metav1.Condition) {
	d.Status.Conditions = conditions
}

func (d *Database) GetDeletionPolicy() DeletionPolicy {
	if d.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return d.Spec.DeletionPolicy
}

func (d *Database) GetFullyQualifiedName() string {
	return d.Status.FullyQualifiedName
}

func (d *Database) GetProviderRef() ProviderReference {
	return d.Spec.ProviderRef
}

func (d *Database) GetSpecName() string {
	return d.Spec.Name
}

func (d *Database) GetUseRole() *string {
	return d.Spec.UseRole
}

func (d *Database) GetObservedGeneration() int64 {
	return d.Status.ObservedGeneration
}

func (d *Database) SetObservedGeneration(val int64) {
	d.Status.ObservedGeneration = val
}

func (d *Database) GetLastAppliedSpecHash() string {
	return d.Status.LastAppliedSpecHash
}

func (d *Database) SetLastAppliedSpecHash(val string) {
	d.Status.LastAppliedSpecHash = val
}

func (d *Database) ValidateSpec() error {
	return d.Spec.Validate()
}

func (d *Database) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(d.Spec)
}

func (d *Database) GetOwner() string {
	if d.Status.ShowOutput != nil {
		return d.Status.ShowOutput.Owner
	}

	return ""
}

func (d *Database) GetTrackedParametersList() []string {
	return d.Status.TrackedParameters
}

func (d *Database) SetTrackedParametersList(val []string) {
	d.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// Schema
// ---------------------------------------------------------------------------

func (s *Schema) GetConditions() []metav1.Condition {
	return s.Status.Conditions
}

func (s *Schema) SetConditions(conditions []metav1.Condition) {
	s.Status.Conditions = conditions
}

func (s *Schema) GetDeletionPolicy() DeletionPolicy {
	if s.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return s.Spec.DeletionPolicy
}

func (s *Schema) GetFullyQualifiedName() string {
	return s.Status.FullyQualifiedName
}

func (s *Schema) GetProviderRef() ProviderReference {
	return s.Spec.ProviderRef
}

func (s *Schema) GetSpecName() string {
	return s.Spec.Name
}

func (s *Schema) GetUseRole() *string {
	return s.Spec.UseRole
}

func (s *Schema) GetObservedGeneration() int64 {
	return s.Status.ObservedGeneration
}

func (s *Schema) SetObservedGeneration(val int64) {
	s.Status.ObservedGeneration = val
}

func (s *Schema) GetLastAppliedSpecHash() string {
	return s.Status.LastAppliedSpecHash
}

func (s *Schema) SetLastAppliedSpecHash(val string) {
	s.Status.LastAppliedSpecHash = val
}

func (s *Schema) ValidateSpec() error {
	return s.Spec.Validate()
}

func (s *Schema) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(s.Spec)
}

func (s *Schema) GetOwner() string {
	if s.Status.ShowOutput != nil {
		return s.Status.ShowOutput.Owner
	}

	return ""
}

func (s *Schema) GetTrackedParametersList() []string {
	return s.Status.TrackedParameters
}

func (s *Schema) SetTrackedParametersList(val []string) {
	s.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// Warehouse
// ---------------------------------------------------------------------------

func (w *Warehouse) GetConditions() []metav1.Condition {
	return w.Status.Conditions
}

func (w *Warehouse) SetConditions(conditions []metav1.Condition) {
	w.Status.Conditions = conditions
}

func (w *Warehouse) GetDeletionPolicy() DeletionPolicy {
	if w.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return w.Spec.DeletionPolicy
}

func (w *Warehouse) GetFullyQualifiedName() string {
	return w.Status.FullyQualifiedName
}

func (w *Warehouse) GetProviderRef() ProviderReference {
	return w.Spec.ProviderRef
}

func (w *Warehouse) GetSpecName() string {
	return w.Spec.Name
}

func (w *Warehouse) GetUseRole() *string {
	return w.Spec.UseRole
}

func (w *Warehouse) GetObservedGeneration() int64 {
	return w.Status.ObservedGeneration
}

func (w *Warehouse) SetObservedGeneration(val int64) {
	w.Status.ObservedGeneration = val
}

func (w *Warehouse) GetLastAppliedSpecHash() string {
	return w.Status.LastAppliedSpecHash
}

func (w *Warehouse) SetLastAppliedSpecHash(val string) {
	w.Status.LastAppliedSpecHash = val
}

func (w *Warehouse) ValidateSpec() error {
	return w.Spec.Validate()
}

func (w *Warehouse) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(w.Spec)
}

func (w *Warehouse) GetOwner() string {
	if w.Status.ShowOutput != nil {
		return w.Status.ShowOutput.Owner
	}

	return ""
}

func (w *Warehouse) GetTrackedParametersList() []string {
	return w.Status.TrackedParameters
}

func (w *Warehouse) SetTrackedParametersList(val []string) {
	w.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// User
// ---------------------------------------------------------------------------

func (u *User) GetConditions() []metav1.Condition {
	return u.Status.Conditions
}

func (u *User) SetConditions(conditions []metav1.Condition) {
	u.Status.Conditions = conditions
}

func (u *User) GetDeletionPolicy() DeletionPolicy {
	if u.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return u.Spec.DeletionPolicy
}

func (u *User) GetFullyQualifiedName() string {
	return u.Status.FullyQualifiedName
}

func (u *User) GetProviderRef() ProviderReference {
	return u.Spec.ProviderRef
}

func (u *User) GetSpecName() string {
	return u.Spec.Name
}

func (u *User) GetUseRole() *string {
	return u.Spec.UseRole
}

func (u *User) GetObservedGeneration() int64 {
	return u.Status.ObservedGeneration
}

func (u *User) SetObservedGeneration(val int64) {
	u.Status.ObservedGeneration = val
}

func (u *User) GetLastAppliedSpecHash() string {
	return u.Status.LastAppliedSpecHash
}

func (u *User) SetLastAppliedSpecHash(val string) {
	u.Status.LastAppliedSpecHash = val
}

func (u *User) ValidateSpec() error {
	return u.Spec.Validate()
}

func (u *User) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(u.Spec)
}

func (u *User) GetOwner() string {
	if u.Status.ShowOutput != nil {
		return u.Status.ShowOutput.Owner
	}

	return ""
}

func (u *User) GetTrackedParametersList() []string {
	return u.Status.TrackedParameters
}

func (u *User) SetTrackedParametersList(val []string) {
	u.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// AccountRole
// ---------------------------------------------------------------------------

func (r *AccountRole) GetConditions() []metav1.Condition {
	return r.Status.Conditions
}

func (r *AccountRole) SetConditions(conditions []metav1.Condition) {
	r.Status.Conditions = conditions
}

func (r *AccountRole) GetDeletionPolicy() DeletionPolicy {
	if r.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return r.Spec.DeletionPolicy
}

func (r *AccountRole) GetFullyQualifiedName() string {
	return r.Status.FullyQualifiedName
}

func (r *AccountRole) GetProviderRef() ProviderReference {
	return r.Spec.ProviderRef
}

func (r *AccountRole) GetSpecName() string {
	return r.Spec.Name
}

func (r *AccountRole) GetUseRole() *string {
	return r.Spec.UseRole
}

func (r *AccountRole) GetObservedGeneration() int64 {
	return r.Status.ObservedGeneration
}

func (r *AccountRole) SetObservedGeneration(val int64) {
	r.Status.ObservedGeneration = val
}

func (r *AccountRole) GetLastAppliedSpecHash() string {
	return r.Status.LastAppliedSpecHash
}

func (r *AccountRole) SetLastAppliedSpecHash(val string) {
	r.Status.LastAppliedSpecHash = val
}

func (r *AccountRole) ValidateSpec() error {
	return r.Spec.Validate()
}

func (r *AccountRole) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(r.Spec)
}

func (r *AccountRole) GetOwner() string {
	if r.Status.ShowOutput != nil {
		return r.Status.ShowOutput.Owner
	}

	return ""
}

func (r *AccountRole) GetTrackedParametersList() []string {
	return r.Status.TrackedParameters
}

func (r *AccountRole) SetTrackedParametersList(val []string) {
	r.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// DatabaseRole
// ---------------------------------------------------------------------------

func (r *DatabaseRole) GetConditions() []metav1.Condition {
	return r.Status.Conditions
}

func (r *DatabaseRole) SetConditions(conditions []metav1.Condition) {
	r.Status.Conditions = conditions
}

func (r *DatabaseRole) GetDeletionPolicy() DeletionPolicy {
	if r.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return r.Spec.DeletionPolicy
}

func (r *DatabaseRole) GetFullyQualifiedName() string {
	return r.Status.FullyQualifiedName
}

func (r *DatabaseRole) GetProviderRef() ProviderReference {
	return r.Spec.ProviderRef
}

func (r *DatabaseRole) GetSpecName() string {
	return r.Spec.Name
}

func (r *DatabaseRole) GetUseRole() *string {
	return r.Spec.UseRole
}

func (r *DatabaseRole) GetObservedGeneration() int64 {
	return r.Status.ObservedGeneration
}

func (r *DatabaseRole) SetObservedGeneration(val int64) {
	r.Status.ObservedGeneration = val
}

func (r *DatabaseRole) GetLastAppliedSpecHash() string {
	return r.Status.LastAppliedSpecHash
}

func (r *DatabaseRole) SetLastAppliedSpecHash(val string) {
	r.Status.LastAppliedSpecHash = val
}

func (r *DatabaseRole) ValidateSpec() error {
	return r.Spec.Validate()
}

func (r *DatabaseRole) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(r.Spec)
}

func (r *DatabaseRole) GetOwner() string {
	if r.Status.ShowOutput != nil {
		return r.Status.ShowOutput.Owner
	}

	return ""
}

func (r *DatabaseRole) GetTrackedParametersList() []string {
	return r.Status.TrackedParameters
}

func (r *DatabaseRole) SetTrackedParametersList(val []string) {
	r.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// Tag
// ---------------------------------------------------------------------------

func (t *Tag) GetConditions() []metav1.Condition {
	return t.Status.Conditions
}

func (t *Tag) SetConditions(conditions []metav1.Condition) {
	t.Status.Conditions = conditions
}

func (t *Tag) GetDeletionPolicy() DeletionPolicy {
	if t.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return t.Spec.DeletionPolicy
}

func (t *Tag) GetFullyQualifiedName() string {
	return t.Status.FullyQualifiedName
}

func (t *Tag) GetProviderRef() ProviderReference {
	return t.Spec.ProviderRef
}

func (t *Tag) GetSpecName() string {
	return t.Spec.Name
}

func (t *Tag) GetUseRole() *string {
	return t.Spec.UseRole
}

func (t *Tag) GetObservedGeneration() int64 {
	return t.Status.ObservedGeneration
}

func (t *Tag) SetObservedGeneration(val int64) {
	t.Status.ObservedGeneration = val
}

func (t *Tag) GetLastAppliedSpecHash() string {
	return t.Status.LastAppliedSpecHash
}

func (t *Tag) SetLastAppliedSpecHash(val string) {
	t.Status.LastAppliedSpecHash = val
}

func (t *Tag) ValidateSpec() error {
	return t.Spec.Validate()
}

func (t *Tag) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(t.Spec)
}

func (t *Tag) GetOwner() string {
	if t.Status.ShowOutput != nil {
		return t.Status.ShowOutput.Owner
	}

	return ""
}

func (t *Tag) GetTrackedParametersList() []string {
	return t.Status.TrackedParameters
}

func (t *Tag) SetTrackedParametersList(val []string) {
	t.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// MaskingPolicy
// ---------------------------------------------------------------------------

func (mp *MaskingPolicy) GetConditions() []metav1.Condition {
	return mp.Status.Conditions
}

func (mp *MaskingPolicy) SetConditions(conditions []metav1.Condition) {
	mp.Status.Conditions = conditions
}

func (mp *MaskingPolicy) GetDeletionPolicy() DeletionPolicy {
	if mp.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return mp.Spec.DeletionPolicy
}

func (mp *MaskingPolicy) GetFullyQualifiedName() string {
	return mp.Status.FullyQualifiedName
}

func (mp *MaskingPolicy) GetProviderRef() ProviderReference {
	return mp.Spec.ProviderRef
}

func (mp *MaskingPolicy) GetSpecName() string {
	return mp.Spec.Name
}

func (mp *MaskingPolicy) GetUseRole() *string {
	return mp.Spec.UseRole
}

func (mp *MaskingPolicy) GetObservedGeneration() int64 {
	return mp.Status.ObservedGeneration
}

func (mp *MaskingPolicy) SetObservedGeneration(val int64) {
	mp.Status.ObservedGeneration = val
}

func (mp *MaskingPolicy) GetLastAppliedSpecHash() string {
	return mp.Status.LastAppliedSpecHash
}

func (mp *MaskingPolicy) SetLastAppliedSpecHash(val string) {
	mp.Status.LastAppliedSpecHash = val
}

func (mp *MaskingPolicy) ValidateSpec() error {
	return mp.Spec.Validate()
}

func (mp *MaskingPolicy) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(mp.Spec)
}

func (mp *MaskingPolicy) GetOwner() string {
	if mp.Status.ShowOutput != nil {
		return mp.Status.ShowOutput.Owner
	}

	return ""
}

func (mp *MaskingPolicy) GetTrackedParametersList() []string {
	return mp.Status.TrackedParameters
}

func (mp *MaskingPolicy) SetTrackedParametersList(val []string) {
	mp.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// RowAccessPolicy
// ---------------------------------------------------------------------------

func (rap *RowAccessPolicy) GetConditions() []metav1.Condition {
	return rap.Status.Conditions
}

func (rap *RowAccessPolicy) SetConditions(conditions []metav1.Condition) {
	rap.Status.Conditions = conditions
}

func (rap *RowAccessPolicy) GetDeletionPolicy() DeletionPolicy {
	if rap.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return rap.Spec.DeletionPolicy
}

func (rap *RowAccessPolicy) GetFullyQualifiedName() string {
	return rap.Status.FullyQualifiedName
}

func (rap *RowAccessPolicy) GetProviderRef() ProviderReference {
	return rap.Spec.ProviderRef
}

func (rap *RowAccessPolicy) GetSpecName() string {
	return rap.Spec.Name
}

func (rap *RowAccessPolicy) GetUseRole() *string {
	return rap.Spec.UseRole
}

func (rap *RowAccessPolicy) GetObservedGeneration() int64 {
	return rap.Status.ObservedGeneration
}

func (rap *RowAccessPolicy) SetObservedGeneration(val int64) {
	rap.Status.ObservedGeneration = val
}

func (rap *RowAccessPolicy) GetLastAppliedSpecHash() string {
	return rap.Status.LastAppliedSpecHash
}

func (rap *RowAccessPolicy) SetLastAppliedSpecHash(val string) {
	rap.Status.LastAppliedSpecHash = val
}

func (rap *RowAccessPolicy) ValidateSpec() error {
	return rap.Spec.Validate()
}

func (rap *RowAccessPolicy) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(rap.Spec)
}

func (rap *RowAccessPolicy) GetOwner() string {
	if rap.Status.ShowOutput != nil {
		return rap.Status.ShowOutput.Owner
	}

	return ""
}

func (rap *RowAccessPolicy) GetTrackedParametersList() []string {
	return rap.Status.TrackedParameters
}

func (rap *RowAccessPolicy) SetTrackedParametersList(val []string) {
	rap.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// Stage
// ---------------------------------------------------------------------------

func (s *Stage) GetConditions() []metav1.Condition {
	return s.Status.Conditions
}

func (s *Stage) SetConditions(conditions []metav1.Condition) {
	s.Status.Conditions = conditions
}

func (s *Stage) GetDeletionPolicy() DeletionPolicy {
	if s.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return s.Spec.DeletionPolicy
}

func (s *Stage) GetFullyQualifiedName() string {
	return s.Status.FullyQualifiedName
}

func (s *Stage) GetProviderRef() ProviderReference {
	return s.Spec.ProviderRef
}

func (s *Stage) GetSpecName() string {
	return s.Spec.Name
}

func (s *Stage) GetUseRole() *string {
	return s.Spec.UseRole
}

func (s *Stage) GetObservedGeneration() int64 {
	return s.Status.ObservedGeneration
}

func (s *Stage) SetObservedGeneration(val int64) {
	s.Status.ObservedGeneration = val
}

func (s *Stage) GetLastAppliedSpecHash() string {
	return s.Status.LastAppliedSpecHash
}

func (s *Stage) SetLastAppliedSpecHash(val string) {
	s.Status.LastAppliedSpecHash = val
}

func (s *Stage) ValidateSpec() error {
	return s.Spec.Validate()
}

func (s *Stage) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(s.Spec)
}

func (s *Stage) GetOwner() string {
	if s.Status.ShowOutput != nil {
		return s.Status.ShowOutput.Owner
	}

	return ""
}

func (s *Stage) GetTrackedParametersList() []string {
	return s.Status.TrackedParameters
}

func (s *Stage) SetTrackedParametersList(val []string) {
	s.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// Stream
// ---------------------------------------------------------------------------

func (s *Stream) GetConditions() []metav1.Condition {
	return s.Status.Conditions
}

func (s *Stream) SetConditions(conditions []metav1.Condition) {
	s.Status.Conditions = conditions
}

func (s *Stream) GetDeletionPolicy() DeletionPolicy {
	if s.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return s.Spec.DeletionPolicy
}

func (s *Stream) GetFullyQualifiedName() string {
	return s.Status.FullyQualifiedName
}

func (s *Stream) GetProviderRef() ProviderReference {
	return s.Spec.ProviderRef
}

func (s *Stream) GetSpecName() string {
	return s.Spec.Name
}

func (s *Stream) GetUseRole() *string {
	return s.Spec.UseRole
}

func (s *Stream) GetObservedGeneration() int64 {
	return s.Status.ObservedGeneration
}

func (s *Stream) SetObservedGeneration(val int64) {
	s.Status.ObservedGeneration = val
}

func (s *Stream) GetLastAppliedSpecHash() string {
	return s.Status.LastAppliedSpecHash
}

func (s *Stream) SetLastAppliedSpecHash(val string) {
	s.Status.LastAppliedSpecHash = val
}

func (s *Stream) ValidateSpec() error {
	return s.Spec.Validate()
}

func (s *Stream) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(s.Spec)
}

func (s *Stream) GetOwner() string {
	if s.Status.ShowOutput != nil {
		return s.Status.ShowOutput.Owner
	}

	return ""
}

func (s *Stream) GetTrackedParametersList() []string {
	return s.Status.TrackedParameters
}

func (s *Stream) SetTrackedParametersList(val []string) {
	s.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// Task
// ---------------------------------------------------------------------------

func (t *Task) GetConditions() []metav1.Condition {
	return t.Status.Conditions
}

func (t *Task) SetConditions(conditions []metav1.Condition) {
	t.Status.Conditions = conditions
}

func (t *Task) GetDeletionPolicy() DeletionPolicy {
	if t.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return t.Spec.DeletionPolicy
}

func (t *Task) GetFullyQualifiedName() string {
	return t.Status.FullyQualifiedName
}

func (t *Task) GetProviderRef() ProviderReference {
	return t.Spec.ProviderRef
}

func (t *Task) GetSpecName() string {
	return t.Spec.Name
}

func (t *Task) GetUseRole() *string {
	return t.Spec.UseRole
}

func (t *Task) GetObservedGeneration() int64 {
	return t.Status.ObservedGeneration
}

func (t *Task) SetObservedGeneration(val int64) {
	t.Status.ObservedGeneration = val
}

func (t *Task) GetLastAppliedSpecHash() string {
	return t.Status.LastAppliedSpecHash
}

func (t *Task) SetLastAppliedSpecHash(val string) {
	t.Status.LastAppliedSpecHash = val
}

func (t *Task) ValidateSpec() error {
	return t.Spec.Validate()
}

func (t *Task) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(t.Spec)
}

func (t *Task) GetOwner() string {
	if t.Status.ShowOutput != nil {
		return t.Status.ShowOutput.Owner
	}

	return ""
}

func (t *Task) GetTrackedParametersList() []string {
	return t.Status.TrackedParameters
}

func (t *Task) SetTrackedParametersList(val []string) {
	t.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// View
// ---------------------------------------------------------------------------

func (v *View) GetConditions() []metav1.Condition {
	return v.Status.Conditions
}

func (v *View) SetConditions(conditions []metav1.Condition) {
	v.Status.Conditions = conditions
}

func (v *View) GetDeletionPolicy() DeletionPolicy {
	if v.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return v.Spec.DeletionPolicy
}

func (v *View) GetFullyQualifiedName() string {
	return v.Status.FullyQualifiedName
}

func (v *View) GetProviderRef() ProviderReference {
	return v.Spec.ProviderRef
}

func (v *View) GetSpecName() string {
	return v.Spec.Name
}

func (v *View) GetUseRole() *string {
	return v.Spec.UseRole
}

func (v *View) GetObservedGeneration() int64 {
	return v.Status.ObservedGeneration
}

func (v *View) SetObservedGeneration(val int64) {
	v.Status.ObservedGeneration = val
}

func (v *View) GetLastAppliedSpecHash() string {
	return v.Status.LastAppliedSpecHash
}

func (v *View) SetLastAppliedSpecHash(val string) {
	v.Status.LastAppliedSpecHash = val
}

func (v *View) ValidateSpec() error {
	return v.Spec.Validate()
}

func (v *View) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(v.Spec)
}

func (v *View) GetOwner() string {
	if v.Status.ShowOutput != nil {
		return v.Status.ShowOutput.Owner
	}

	return ""
}

func (v *View) GetTrackedParametersList() []string {
	return v.Status.TrackedParameters
}

func (v *View) SetTrackedParametersList(val []string) {
	v.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// Table
// ---------------------------------------------------------------------------

func (t *Table) GetConditions() []metav1.Condition {
	return t.Status.Conditions
}

func (t *Table) SetConditions(conditions []metav1.Condition) {
	t.Status.Conditions = conditions
}

func (t *Table) GetDeletionPolicy() DeletionPolicy {
	if t.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return t.Spec.DeletionPolicy
}

func (t *Table) GetFullyQualifiedName() string {
	return t.Status.FullyQualifiedName
}

func (t *Table) GetProviderRef() ProviderReference {
	return t.Spec.ProviderRef
}

func (t *Table) GetSpecName() string {
	return t.Spec.Name
}

func (t *Table) GetUseRole() *string {
	return t.Spec.UseRole
}

func (t *Table) GetObservedGeneration() int64 {
	return t.Status.ObservedGeneration
}

func (t *Table) SetObservedGeneration(val int64) {
	t.Status.ObservedGeneration = val
}

func (t *Table) GetLastAppliedSpecHash() string {
	return t.Status.LastAppliedSpecHash
}

func (t *Table) SetLastAppliedSpecHash(val string) {
	t.Status.LastAppliedSpecHash = val
}

func (t *Table) ValidateSpec() error {
	return t.Spec.Validate()
}

func (t *Table) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(t.Spec)
}

func (t *Table) GetOwner() string {
	if t.Status.ShowOutput != nil {
		return t.Status.ShowOutput.Owner
	}

	return ""
}

func (t *Table) GetTrackedParametersList() []string {
	return t.Status.TrackedParameters
}

func (t *Table) SetTrackedParametersList(val []string) {
	t.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// NetworkPolicy
// ---------------------------------------------------------------------------

func (np *NetworkPolicy) GetConditions() []metav1.Condition {
	return np.Status.Conditions
}

func (np *NetworkPolicy) SetConditions(conditions []metav1.Condition) {
	np.Status.Conditions = conditions
}

func (np *NetworkPolicy) GetDeletionPolicy() DeletionPolicy {
	if np.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return np.Spec.DeletionPolicy
}

func (np *NetworkPolicy) GetFullyQualifiedName() string {
	return np.Status.FullyQualifiedName
}

func (np *NetworkPolicy) GetProviderRef() ProviderReference {
	return np.Spec.ProviderRef
}

func (np *NetworkPolicy) GetSpecName() string {
	return np.Spec.Name
}

func (np *NetworkPolicy) GetUseRole() *string {
	return np.Spec.UseRole
}

func (np *NetworkPolicy) GetObservedGeneration() int64 {
	return np.Status.ObservedGeneration
}

func (np *NetworkPolicy) SetObservedGeneration(val int64) {
	np.Status.ObservedGeneration = val
}

func (np *NetworkPolicy) GetLastAppliedSpecHash() string {
	return np.Status.LastAppliedSpecHash
}

func (np *NetworkPolicy) SetLastAppliedSpecHash(val string) {
	np.Status.LastAppliedSpecHash = val
}

func (np *NetworkPolicy) ValidateSpec() error {
	return np.Spec.Validate()
}

func (np *NetworkPolicy) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(np.Spec)
}

func (np *NetworkPolicy) GetOwner() string {
	// SHOW NETWORK POLICIES does not return an owner column.
	return ""
}

func (np *NetworkPolicy) GetTrackedParametersList() []string {
	return np.Status.TrackedParameters
}

func (np *NetworkPolicy) SetTrackedParametersList(val []string) {
	np.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// ResourceMonitor
// ---------------------------------------------------------------------------

func (rm *ResourceMonitor) GetConditions() []metav1.Condition {
	return rm.Status.Conditions
}

func (rm *ResourceMonitor) SetConditions(conditions []metav1.Condition) {
	rm.Status.Conditions = conditions
}

func (rm *ResourceMonitor) GetDeletionPolicy() DeletionPolicy {
	if rm.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return rm.Spec.DeletionPolicy
}

func (rm *ResourceMonitor) GetFullyQualifiedName() string {
	return rm.Status.FullyQualifiedName
}

func (rm *ResourceMonitor) GetProviderRef() ProviderReference {
	return rm.Spec.ProviderRef
}

func (rm *ResourceMonitor) GetSpecName() string {
	return rm.Spec.Name
}

func (rm *ResourceMonitor) GetUseRole() *string {
	return rm.Spec.UseRole
}

func (rm *ResourceMonitor) GetObservedGeneration() int64 {
	return rm.Status.ObservedGeneration
}

func (rm *ResourceMonitor) SetObservedGeneration(val int64) {
	rm.Status.ObservedGeneration = val
}

func (rm *ResourceMonitor) GetLastAppliedSpecHash() string {
	return rm.Status.LastAppliedSpecHash
}

func (rm *ResourceMonitor) SetLastAppliedSpecHash(val string) {
	rm.Status.LastAppliedSpecHash = val
}

func (rm *ResourceMonitor) ValidateSpec() error {
	return rm.Spec.Validate()
}

func (rm *ResourceMonitor) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(rm.Spec)
}

func (rm *ResourceMonitor) GetOwner() string {
	// SHOW RESOURCE MONITORS does not return an owner column.
	return ""
}

func (rm *ResourceMonitor) GetTrackedParametersList() []string {
	return rm.Status.TrackedParameters
}

func (rm *ResourceMonitor) SetTrackedParametersList(val []string) {
	rm.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// StorageIntegration
// ---------------------------------------------------------------------------

func (si *StorageIntegration) GetConditions() []metav1.Condition {
	return si.Status.Conditions
}

func (si *StorageIntegration) SetConditions(conditions []metav1.Condition) {
	si.Status.Conditions = conditions
}

func (si *StorageIntegration) GetDeletionPolicy() DeletionPolicy {
	if si.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return si.Spec.DeletionPolicy
}

func (si *StorageIntegration) GetFullyQualifiedName() string {
	return si.Status.FullyQualifiedName
}

func (si *StorageIntegration) GetProviderRef() ProviderReference {
	return si.Spec.ProviderRef
}

func (si *StorageIntegration) GetSpecName() string {
	return si.Spec.Name
}

func (si *StorageIntegration) GetUseRole() *string {
	return si.Spec.UseRole
}

func (si *StorageIntegration) GetObservedGeneration() int64 {
	return si.Status.ObservedGeneration
}

func (si *StorageIntegration) SetObservedGeneration(val int64) {
	si.Status.ObservedGeneration = val
}

func (si *StorageIntegration) GetLastAppliedSpecHash() string {
	return si.Status.LastAppliedSpecHash
}

func (si *StorageIntegration) SetLastAppliedSpecHash(val string) {
	si.Status.LastAppliedSpecHash = val
}

func (si *StorageIntegration) ValidateSpec() error {
	return si.Spec.Validate()
}

func (si *StorageIntegration) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(si.Spec)
}

func (si *StorageIntegration) GetOwner() string {
	// SHOW STORAGE INTEGRATIONS does not return an owner column.
	return ""
}

func (si *StorageIntegration) GetTrackedParametersList() []string {
	return si.Status.TrackedParameters
}

func (si *StorageIntegration) SetTrackedParametersList(val []string) {
	si.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// FileFormat
// ---------------------------------------------------------------------------

func (ff *FileFormat) GetConditions() []metav1.Condition {
	return ff.Status.Conditions
}

func (ff *FileFormat) SetConditions(conditions []metav1.Condition) {
	ff.Status.Conditions = conditions
}

func (ff *FileFormat) GetDeletionPolicy() DeletionPolicy {
	if ff.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return ff.Spec.DeletionPolicy
}

func (ff *FileFormat) GetFullyQualifiedName() string {
	return ff.Status.FullyQualifiedName
}

func (ff *FileFormat) GetProviderRef() ProviderReference {
	return ff.Spec.ProviderRef
}

func (ff *FileFormat) GetSpecName() string {
	return ff.Spec.Name
}

func (ff *FileFormat) GetUseRole() *string {
	return ff.Spec.UseRole
}

func (ff *FileFormat) GetObservedGeneration() int64 {
	return ff.Status.ObservedGeneration
}

func (ff *FileFormat) SetObservedGeneration(val int64) {
	ff.Status.ObservedGeneration = val
}

func (ff *FileFormat) GetLastAppliedSpecHash() string {
	return ff.Status.LastAppliedSpecHash
}

func (ff *FileFormat) SetLastAppliedSpecHash(val string) {
	ff.Status.LastAppliedSpecHash = val
}

func (ff *FileFormat) ValidateSpec() error {
	return ff.Spec.Validate()
}

func (ff *FileFormat) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(ff.Spec)
}

func (ff *FileFormat) GetOwner() string {
	if ff.Status.ShowOutput != nil {
		return ff.Status.ShowOutput.Owner
	}

	return ""
}

func (ff *FileFormat) GetTrackedParametersList() []string {
	return ff.Status.TrackedParameters
}

func (ff *FileFormat) SetTrackedParametersList(val []string) {
	ff.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// Pipe
// ---------------------------------------------------------------------------

func (p *Pipe) GetConditions() []metav1.Condition {
	return p.Status.Conditions
}

func (p *Pipe) SetConditions(conditions []metav1.Condition) {
	p.Status.Conditions = conditions
}

func (p *Pipe) GetDeletionPolicy() DeletionPolicy {
	if p.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return p.Spec.DeletionPolicy
}

func (p *Pipe) GetFullyQualifiedName() string {
	return p.Status.FullyQualifiedName
}

func (p *Pipe) GetProviderRef() ProviderReference {
	return p.Spec.ProviderRef
}

func (p *Pipe) GetSpecName() string {
	return p.Spec.Name
}

func (p *Pipe) GetUseRole() *string {
	return p.Spec.UseRole
}

func (p *Pipe) GetObservedGeneration() int64 {
	return p.Status.ObservedGeneration
}

func (p *Pipe) SetObservedGeneration(val int64) {
	p.Status.ObservedGeneration = val
}

func (p *Pipe) GetLastAppliedSpecHash() string {
	return p.Status.LastAppliedSpecHash
}

func (p *Pipe) SetLastAppliedSpecHash(val string) {
	p.Status.LastAppliedSpecHash = val
}

func (p *Pipe) ValidateSpec() error {
	return p.Spec.Validate()
}

func (p *Pipe) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(p.Spec)
}

func (p *Pipe) GetOwner() string {
	if p.Status.ShowOutput != nil {
		return p.Status.ShowOutput.Owner
	}

	return ""
}

func (p *Pipe) GetTrackedParametersList() []string {
	return p.Status.TrackedParameters
}

func (p *Pipe) SetTrackedParametersList(val []string) {
	p.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// DynamicTable
// ---------------------------------------------------------------------------

func (dt *DynamicTable) GetConditions() []metav1.Condition {
	return dt.Status.Conditions
}

func (dt *DynamicTable) SetConditions(conditions []metav1.Condition) {
	dt.Status.Conditions = conditions
}

func (dt *DynamicTable) GetDeletionPolicy() DeletionPolicy {
	if dt.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return dt.Spec.DeletionPolicy
}

func (dt *DynamicTable) GetFullyQualifiedName() string {
	return dt.Status.FullyQualifiedName
}

func (dt *DynamicTable) GetProviderRef() ProviderReference {
	return dt.Spec.ProviderRef
}

func (dt *DynamicTable) GetSpecName() string {
	return dt.Spec.Name
}

func (dt *DynamicTable) GetUseRole() *string {
	return dt.Spec.UseRole
}

func (dt *DynamicTable) GetObservedGeneration() int64 {
	return dt.Status.ObservedGeneration
}

func (dt *DynamicTable) SetObservedGeneration(val int64) {
	dt.Status.ObservedGeneration = val
}

func (dt *DynamicTable) GetLastAppliedSpecHash() string {
	return dt.Status.LastAppliedSpecHash
}

func (dt *DynamicTable) SetLastAppliedSpecHash(val string) {
	dt.Status.LastAppliedSpecHash = val
}

func (dt *DynamicTable) ValidateSpec() error {
	return dt.Spec.Validate()
}

func (dt *DynamicTable) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(dt.Spec)
}

func (dt *DynamicTable) GetOwner() string {
	if dt.Status.ShowOutput != nil {
		return dt.Status.ShowOutput.Owner
	}

	return ""
}

func (dt *DynamicTable) GetTrackedParametersList() []string {
	return dt.Status.TrackedParameters
}

func (dt *DynamicTable) SetTrackedParametersList(val []string) {
	dt.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// AccountRoleGrant
// ---------------------------------------------------------------------------

func (r *AccountRoleGrant) GetConditions() []metav1.Condition {
	return r.Status.Conditions
}

func (r *AccountRoleGrant) SetConditions(conditions []metav1.Condition) {
	r.Status.Conditions = conditions
}

func (r *AccountRoleGrant) GetDeletionPolicy() DeletionPolicy {
	if r.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return r.Spec.DeletionPolicy
}

func (r *AccountRoleGrant) GetFullyQualifiedName() string {
	return r.Status.FullyQualifiedName
}

func (r *AccountRoleGrant) GetProviderRef() ProviderReference {
	return r.Spec.ProviderRef
}

func (r *AccountRoleGrant) GetUseRole() *string {
	return r.Spec.UseRole
}

func (r *AccountRoleGrant) GetObservedGeneration() int64 {
	return r.Status.ObservedGeneration
}

func (r *AccountRoleGrant) SetObservedGeneration(val int64) {
	r.Status.ObservedGeneration = val
}

func (r *AccountRoleGrant) GetLastAppliedSpecHash() string {
	return r.Status.LastAppliedSpecHash
}

func (r *AccountRoleGrant) SetLastAppliedSpecHash(val string) {
	r.Status.LastAppliedSpecHash = val
}

func (r *AccountRoleGrant) ValidateSpec() error {
	return r.Spec.Validate()
}

func (r *AccountRoleGrant) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(r.Spec)
}

func (r *AccountRoleGrant) GetOwner() string {
	if r.Status.ShowOutput != nil {
		return r.Status.ShowOutput.GrantedBy
	}

	return ""
}

func (r *AccountRoleGrant) GetTrackedParametersList() []string { return nil }

func (r *AccountRoleGrant) SetTrackedParametersList(_ []string) {}

// ---------------------------------------------------------------------------
// DatabaseRoleGrant
// ---------------------------------------------------------------------------

func (r *DatabaseRoleGrant) GetConditions() []metav1.Condition {
	return r.Status.Conditions
}

func (r *DatabaseRoleGrant) SetConditions(conditions []metav1.Condition) {
	r.Status.Conditions = conditions
}

func (r *DatabaseRoleGrant) GetDeletionPolicy() DeletionPolicy {
	if r.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return r.Spec.DeletionPolicy
}

func (r *DatabaseRoleGrant) GetFullyQualifiedName() string {
	return r.Status.FullyQualifiedName
}

func (r *DatabaseRoleGrant) GetProviderRef() ProviderReference {
	return r.Spec.ProviderRef
}

func (r *DatabaseRoleGrant) GetUseRole() *string {
	return r.Spec.UseRole
}

func (r *DatabaseRoleGrant) GetObservedGeneration() int64 {
	return r.Status.ObservedGeneration
}

func (r *DatabaseRoleGrant) SetObservedGeneration(val int64) {
	r.Status.ObservedGeneration = val
}

func (r *DatabaseRoleGrant) GetLastAppliedSpecHash() string {
	return r.Status.LastAppliedSpecHash
}

func (r *DatabaseRoleGrant) SetLastAppliedSpecHash(val string) {
	r.Status.LastAppliedSpecHash = val
}

func (r *DatabaseRoleGrant) ValidateSpec() error {
	return r.Spec.Validate()
}

func (r *DatabaseRoleGrant) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(r.Spec)
}

func (r *DatabaseRoleGrant) GetOwner() string {
	if r.Status.ShowOutput != nil {
		return r.Status.ShowOutput.GrantedBy
	}

	return ""
}

func (r *DatabaseRoleGrant) GetTrackedParametersList() []string { return nil }

func (r *DatabaseRoleGrant) SetTrackedParametersList(_ []string) {}

// ---------------------------------------------------------------------------
// ShareGrant
// ---------------------------------------------------------------------------

func (r *ShareGrant) GetConditions() []metav1.Condition {
	return r.Status.Conditions
}

func (r *ShareGrant) SetConditions(conditions []metav1.Condition) {
	r.Status.Conditions = conditions
}

func (r *ShareGrant) GetDeletionPolicy() DeletionPolicy {
	if r.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return r.Spec.DeletionPolicy
}

func (r *ShareGrant) GetFullyQualifiedName() string {
	return r.Status.FullyQualifiedName
}

func (r *ShareGrant) GetProviderRef() ProviderReference {
	return r.Spec.ProviderRef
}

func (r *ShareGrant) GetUseRole() *string {
	return r.Spec.UseRole
}

func (r *ShareGrant) GetObservedGeneration() int64 {
	return r.Status.ObservedGeneration
}

func (r *ShareGrant) SetObservedGeneration(val int64) {
	r.Status.ObservedGeneration = val
}

func (r *ShareGrant) GetLastAppliedSpecHash() string {
	return r.Status.LastAppliedSpecHash
}

func (r *ShareGrant) SetLastAppliedSpecHash(val string) {
	r.Status.LastAppliedSpecHash = val
}

func (r *ShareGrant) ValidateSpec() error {
	return r.Spec.Validate()
}

func (r *ShareGrant) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(r.Spec)
}

func (r *ShareGrant) GetOwner() string {
	if r.Status.ShowOutput != nil {
		return r.Status.ShowOutput.GrantedBy
	}

	return ""
}

func (r *ShareGrant) GetTrackedParametersList() []string { return nil }

func (r *ShareGrant) SetTrackedParametersList(_ []string) {}

// ---------------------------------------------------------------------------
// GrantOwnership
// ---------------------------------------------------------------------------

func (g *GrantOwnership) GetConditions() []metav1.Condition {
	return g.Status.Conditions
}

func (g *GrantOwnership) SetConditions(conditions []metav1.Condition) {
	g.Status.Conditions = conditions
}

func (g *GrantOwnership) GetDeletionPolicy() DeletionPolicy {
	if g.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return g.Spec.DeletionPolicy
}

func (g *GrantOwnership) GetFullyQualifiedName() string {
	return g.Status.FullyQualifiedName
}

func (g *GrantOwnership) GetProviderRef() ProviderReference {
	return g.Spec.ProviderRef
}

func (g *GrantOwnership) GetUseRole() *string {
	return g.Spec.UseRole
}

func (g *GrantOwnership) GetObservedGeneration() int64 {
	return g.Status.ObservedGeneration
}

func (g *GrantOwnership) SetObservedGeneration(val int64) {
	g.Status.ObservedGeneration = val
}

func (g *GrantOwnership) GetLastAppliedSpecHash() string {
	return g.Status.LastAppliedSpecHash
}

func (g *GrantOwnership) SetLastAppliedSpecHash(val string) {
	g.Status.LastAppliedSpecHash = val
}

func (g *GrantOwnership) ValidateSpec() error {
	return g.Spec.Validate()
}

func (g *GrantOwnership) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(g.Spec)
}

func (g *GrantOwnership) GetOwner() string {
	return ""
}

func (g *GrantOwnership) GetTrackedParametersList() []string { return nil }

func (g *GrantOwnership) SetTrackedParametersList(_ []string) {}
