// Code generated by hack/gen-accessors/main.go; DO NOT EDIT.

package v1alpha1

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

// ---------------------------------------------------------------------------
// Database
// ---------------------------------------------------------------------------

func (d *Database) GetConditions() []metav1.Condition {
	return d.Status.Conditions
}

func (d *Database) SetConditions(conditions []metav1.Condition) {
	d.Status.Conditions = conditions
}

func (d *Database) GetDeletionPolicy() DeletionPolicy {
	if d.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return d.Spec.DeletionPolicy
}

func (d *Database) GetFullyQualifiedName() string {
	return d.Status.FullyQualifiedName
}

func (d *Database) GetProviderRef() ProviderReference {
	return d.Spec.ProviderRef
}

func (d *Database) GetSpecName() string {
	return d.Spec.Name
}

func (d *Database) GetUseRole() *string {
	return d.Spec.UseRole
}

func (d *Database) GetPaused() bool {
	return d.Spec.Paused
}

func (d *Database) GetManagementPolicies() ManagementPolicies {
	return d.Spec.ManagementPolicies
}

func (d *Database) SetCreateOrAlter(val *bool) {
	d.Spec.ManagementPolicies.CreateOrAlter = val
}

func (d *Database) GetObservedGeneration() int64 {
	return d.Status.ObservedGeneration
}

func (d *Database) SetObservedGeneration(val int64) {
	d.Status.ObservedGeneration = val
}

func (d *Database) GetLastAppliedSpecHash() string {
	return d.Status.LastAppliedSpecHash
}

func (d *Database) SetLastAppliedSpecHash(val string) {
	d.Status.LastAppliedSpecHash = val
}

func (d *Database) ValidateSpec() error {
	return d.Spec.Validate()
}

func (d *Database) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(d.Spec)
}

func (d *Database) GetOwner() string {
	if d.Status.ShowOutput != nil {
		return d.Status.ShowOutput.Owner
	}

	return ""
}

func (d *Database) GetTrackedParametersList() []string {
	return d.Status.TrackedParameters
}

func (d *Database) SetTrackedParametersList(val []string) {
	d.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// Schema
// ---------------------------------------------------------------------------

func (s *Schema) GetConditions() []metav1.Condition {
	return s.Status.Conditions
}

func (s *Schema) SetConditions(conditions []metav1.Condition) {
	s.Status.Conditions = conditions
}

func (s *Schema) GetDeletionPolicy() DeletionPolicy {
	if s.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return s.Spec.DeletionPolicy
}

func (s *Schema) GetFullyQualifiedName() string {
	return s.Status.FullyQualifiedName
}

func (s *Schema) GetProviderRef() ProviderReference {
	return s.Spec.ProviderRef
}

func (s *Schema) GetSpecName() string {
	return s.Spec.Name
}

func (s *Schema) GetUseRole() *string {
	return s.Spec.UseRole
}

func (s *Schema) GetPaused() bool {
	return s.Spec.Paused
}

func (s *Schema) GetManagementPolicies() ManagementPolicies {
	return s.Spec.ManagementPolicies
}

func (s *Schema) SetCreateOrAlter(val *bool) {
	s.Spec.ManagementPolicies.CreateOrAlter = val
}

func (s *Schema) GetObservedGeneration() int64 {
	return s.Status.ObservedGeneration
}

func (s *Schema) SetObservedGeneration(val int64) {
	s.Status.ObservedGeneration = val
}

func (s *Schema) GetLastAppliedSpecHash() string {
	return s.Status.LastAppliedSpecHash
}

func (s *Schema) SetLastAppliedSpecHash(val string) {
	s.Status.LastAppliedSpecHash = val
}

func (s *Schema) ValidateSpec() error {
	return s.Spec.Validate()
}

func (s *Schema) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(s.Spec)
}

func (s *Schema) GetOwner() string {
	if s.Status.ShowOutput != nil {
		return s.Status.ShowOutput.Owner
	}

	return ""
}

func (s *Schema) GetTrackedParametersList() []string {
	return s.Status.TrackedParameters
}

func (s *Schema) SetTrackedParametersList(val []string) {
	s.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// Warehouse
// ---------------------------------------------------------------------------

func (w *Warehouse) GetConditions() []metav1.Condition {
	return w.Status.Conditions
}

func (w *Warehouse) SetConditions(conditions []metav1.Condition) {
	w.Status.Conditions = conditions
}

func (w *Warehouse) GetDeletionPolicy() DeletionPolicy {
	if w.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return w.Spec.DeletionPolicy
}

func (w *Warehouse) GetFullyQualifiedName() string {
	return w.Status.FullyQualifiedName
}

func (w *Warehouse) GetProviderRef() ProviderReference {
	return w.Spec.ProviderRef
}

func (w *Warehouse) GetSpecName() string {
	return w.Spec.Name
}

func (w *Warehouse) GetUseRole() *string {
	return w.Spec.UseRole
}

func (w *Warehouse) GetPaused() bool {
	return w.Spec.Paused
}

func (w *Warehouse) GetManagementPolicies() ManagementPolicies {
	return w.Spec.ManagementPolicies
}

func (w *Warehouse) SetCreateOrAlter(val *bool) {
	w.Spec.ManagementPolicies.CreateOrAlter = val
}

func (w *Warehouse) GetObservedGeneration() int64 {
	return w.Status.ObservedGeneration
}

func (w *Warehouse) SetObservedGeneration(val int64) {
	w.Status.ObservedGeneration = val
}

func (w *Warehouse) GetLastAppliedSpecHash() string {
	return w.Status.LastAppliedSpecHash
}

func (w *Warehouse) SetLastAppliedSpecHash(val string) {
	w.Status.LastAppliedSpecHash = val
}

func (w *Warehouse) ValidateSpec() error {
	return w.Spec.Validate()
}

func (w *Warehouse) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(w.Spec)
}

func (w *Warehouse) GetOwner() string {
	if w.Status.ShowOutput != nil {
		return w.Status.ShowOutput.Owner
	}

	return ""
}

func (w *Warehouse) GetTrackedParametersList() []string {
	return w.Status.TrackedParameters
}

func (w *Warehouse) SetTrackedParametersList(val []string) {
	w.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// User
// ---------------------------------------------------------------------------

func (u *User) GetConditions() []metav1.Condition {
	return u.Status.Conditions
}

func (u *User) SetConditions(conditions []metav1.Condition) {
	u.Status.Conditions = conditions
}

func (u *User) GetDeletionPolicy() DeletionPolicy {
	if u.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return u.Spec.DeletionPolicy
}

func (u *User) GetFullyQualifiedName() string {
	return u.Status.FullyQualifiedName
}

func (u *User) GetProviderRef() ProviderReference {
	return u.Spec.ProviderRef
}

func (u *User) GetSpecName() string {
	return u.Spec.Name
}

func (u *User) GetUseRole() *string {
	return u.Spec.UseRole
}

func (u *User) GetPaused() bool {
	return u.Spec.Paused
}

func (u *User) GetManagementPolicies() ManagementPolicies {
	return u.Spec.ManagementPolicies
}

func (u *User) SetCreateOrAlter(val *bool) {
	u.Spec.ManagementPolicies.CreateOrAlter = val
}

func (u *User) GetObservedGeneration() int64 {
	return u.Status.ObservedGeneration
}

func (u *User) SetObservedGeneration(val int64) {
	u.Status.ObservedGeneration = val
}

func (u *User) GetLastAppliedSpecHash() string {
	return u.Status.LastAppliedSpecHash
}

func (u *User) SetLastAppliedSpecHash(val string) {
	u.Status.LastAppliedSpecHash = val
}

func (u *User) ValidateSpec() error {
	return u.Spec.Validate()
}

func (u *User) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(u.Spec)
}

func (u *User) GetOwner() string {
	if u.Status.ShowOutput != nil {
		return u.Status.ShowOutput.Owner
	}

	return ""
}

func (u *User) GetTrackedParametersList() []string {
	return u.Status.TrackedParameters
}

func (u *User) SetTrackedParametersList(val []string) {
	u.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// AccountRole
// ---------------------------------------------------------------------------

func (r *AccountRole) GetConditions() []metav1.Condition {
	return r.Status.Conditions
}

func (r *AccountRole) SetConditions(conditions []metav1.Condition) {
	r.Status.Conditions = conditions
}

func (r *AccountRole) GetDeletionPolicy() DeletionPolicy {
	if r.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return r.Spec.DeletionPolicy
}

func (r *AccountRole) GetFullyQualifiedName() string {
	return r.Status.FullyQualifiedName
}

func (r *AccountRole) GetProviderRef() ProviderReference {
	return r.Spec.ProviderRef
}

func (r *AccountRole) GetSpecName() string {
	return r.Spec.Name
}

func (r *AccountRole) GetUseRole() *string {
	return r.Spec.UseRole
}

func (r *AccountRole) GetPaused() bool {
	return r.Spec.Paused
}

func (r *AccountRole) GetManagementPolicies() ManagementPolicies {
	return r.Spec.ManagementPolicies
}

func (r *AccountRole) SetCreateOrAlter(val *bool) {
	r.Spec.ManagementPolicies.CreateOrAlter = val
}

func (r *AccountRole) GetObservedGeneration() int64 {
	return r.Status.ObservedGeneration
}

func (r *AccountRole) SetObservedGeneration(val int64) {
	r.Status.ObservedGeneration = val
}

func (r *AccountRole) GetLastAppliedSpecHash() string {
	return r.Status.LastAppliedSpecHash
}

func (r *AccountRole) SetLastAppliedSpecHash(val string) {
	r.Status.LastAppliedSpecHash = val
}

func (r *AccountRole) ValidateSpec() error {
	return r.Spec.Validate()
}

func (r *AccountRole) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(r.Spec)
}

func (r *AccountRole) GetOwner() string {
	if r.Status.ShowOutput != nil {
		return r.Status.ShowOutput.Owner
	}

	return ""
}

func (r *AccountRole) GetTrackedParametersList() []string {
	return r.Status.TrackedParameters
}

func (r *AccountRole) SetTrackedParametersList(val []string) {
	r.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// DatabaseRole
// ---------------------------------------------------------------------------

func (r *DatabaseRole) GetConditions() []metav1.Condition {
	return r.Status.Conditions
}

func (r *DatabaseRole) SetConditions(conditions []metav1.Condition) {
	r.Status.Conditions = conditions
}

func (r *DatabaseRole) GetDeletionPolicy() DeletionPolicy {
	if r.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return r.Spec.DeletionPolicy
}

func (r *DatabaseRole) GetFullyQualifiedName() string {
	return r.Status.FullyQualifiedName
}

func (r *DatabaseRole) GetProviderRef() ProviderReference {
	return r.Spec.ProviderRef
}

func (r *DatabaseRole) GetSpecName() string {
	return r.Spec.Name
}

func (r *DatabaseRole) GetUseRole() *string {
	return r.Spec.UseRole
}

func (r *DatabaseRole) GetPaused() bool {
	return r.Spec.Paused
}

func (r *DatabaseRole) GetManagementPolicies() ManagementPolicies {
	return r.Spec.ManagementPolicies
}

func (r *DatabaseRole) SetCreateOrAlter(val *bool) {
	r.Spec.ManagementPolicies.CreateOrAlter = val
}

func (r *DatabaseRole) GetObservedGeneration() int64 {
	return r.Status.ObservedGeneration
}

func (r *DatabaseRole) SetObservedGeneration(val int64) {
	r.Status.ObservedGeneration = val
}

func (r *DatabaseRole) GetLastAppliedSpecHash() string {
	return r.Status.LastAppliedSpecHash
}

func (r *DatabaseRole) SetLastAppliedSpecHash(val string) {
	r.Status.LastAppliedSpecHash = val
}

func (r *DatabaseRole) ValidateSpec() error {
	return r.Spec.Validate()
}

func (r *DatabaseRole) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(r.Spec)
}

func (r *DatabaseRole) GetOwner() string {
	if r.Status.ShowOutput != nil {
		return r.Status.ShowOutput.Owner
	}

	return ""
}

func (r *DatabaseRole) GetTrackedParametersList() []string {
	return r.Status.TrackedParameters
}

func (r *DatabaseRole) SetTrackedParametersList(val []string) {
	r.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// Tag
// ---------------------------------------------------------------------------

func (t *Tag) GetConditions() []metav1.Condition {
	return t.Status.Conditions
}

func (t *Tag) SetConditions(conditions []metav1.Condition) {
	t.Status.Conditions = conditions
}

func (t *Tag) GetDeletionPolicy() DeletionPolicy {
	if t.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return t.Spec.DeletionPolicy
}

func (t *Tag) GetFullyQualifiedName() string {
	return t.Status.FullyQualifiedName
}

func (t *Tag) GetProviderRef() ProviderReference {
	return t.Spec.ProviderRef
}

func (t *Tag) GetSpecName() string {
	return t.Spec.Name
}

func (t *Tag) GetUseRole() *string {
	return t.Spec.UseRole
}

func (t *Tag) GetPaused() bool {
	return t.Spec.Paused
}

func (t *Tag) GetManagementPolicies() ManagementPolicies {
	return t.Spec.ManagementPolicies
}

func (t *Tag) SetCreateOrAlter(val *bool) {
	t.Spec.ManagementPolicies.CreateOrAlter = val
}

func (t *Tag) GetObservedGeneration() int64 {
	return t.Status.ObservedGeneration
}

func (t *Tag) SetObservedGeneration(val int64) {
	t.Status.ObservedGeneration = val
}

func (t *Tag) GetLastAppliedSpecHash() string {
	return t.Status.LastAppliedSpecHash
}

func (t *Tag) SetLastAppliedSpecHash(val string) {
	t.Status.LastAppliedSpecHash = val
}

func (t *Tag) ValidateSpec() error {
	return t.Spec.Validate()
}

func (t *Tag) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(t.Spec)
}

func (t *Tag) GetOwner() string {
	if t.Status.ShowOutput != nil {
		return t.Status.ShowOutput.Owner
	}

	return ""
}

func (t *Tag) GetTrackedParametersList() []string {
	return t.Status.TrackedParameters
}

func (t *Tag) SetTrackedParametersList(val []string) {
	t.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// MaskingPolicy
// ---------------------------------------------------------------------------

func (mp *MaskingPolicy) GetConditions() []metav1.Condition {
	return mp.Status.Conditions
}

func (mp *MaskingPolicy) SetConditions(conditions []metav1.Condition) {
	mp.Status.Conditions = conditions
}

func (mp *MaskingPolicy) GetDeletionPolicy() DeletionPolicy {
	if mp.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return mp.Spec.DeletionPolicy
}

func (mp *MaskingPolicy) GetFullyQualifiedName() string {
	return mp.Status.FullyQualifiedName
}

func (mp *MaskingPolicy) GetProviderRef() ProviderReference {
	return mp.Spec.ProviderRef
}

func (mp *MaskingPolicy) GetSpecName() string {
	return mp.Spec.Name
}

func (mp *MaskingPolicy) GetUseRole() *string {
	return mp.Spec.UseRole
}

func (mp *MaskingPolicy) GetPaused() bool {
	return mp.Spec.Paused
}

func (mp *MaskingPolicy) GetManagementPolicies() ManagementPolicies {
	return mp.Spec.ManagementPolicies
}

func (mp *MaskingPolicy) SetCreateOrAlter(val *bool) {
	mp.Spec.ManagementPolicies.CreateOrAlter = val
}

func (mp *MaskingPolicy) GetObservedGeneration() int64 {
	return mp.Status.ObservedGeneration
}

func (mp *MaskingPolicy) SetObservedGeneration(val int64) {
	mp.Status.ObservedGeneration = val
}

func (mp *MaskingPolicy) GetLastAppliedSpecHash() string {
	return mp.Status.LastAppliedSpecHash
}

func (mp *MaskingPolicy) SetLastAppliedSpecHash(val string) {
	mp.Status.LastAppliedSpecHash = val
}

func (mp *MaskingPolicy) ValidateSpec() error {
	return mp.Spec.Validate()
}

func (mp *MaskingPolicy) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(mp.Spec)
}

func (mp *MaskingPolicy) GetOwner() string {
	if mp.Status.ShowOutput != nil {
		return mp.Status.ShowOutput.Owner
	}

	return ""
}

func (mp *MaskingPolicy) GetTrackedParametersList() []string {
	return mp.Status.TrackedParameters
}

func (mp *MaskingPolicy) SetTrackedParametersList(val []string) {
	mp.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// RowAccessPolicy
// ---------------------------------------------------------------------------

func (rap *RowAccessPolicy) GetConditions() []metav1.Condition {
	return rap.Status.Conditions
}

func (rap *RowAccessPolicy) SetConditions(conditions []metav1.Condition) {
	rap.Status.Conditions = conditions
}

func (rap *RowAccessPolicy) GetDeletionPolicy() DeletionPolicy {
	if rap.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return rap.Spec.DeletionPolicy
}

func (rap *RowAccessPolicy) GetFullyQualifiedName() string {
	return rap.Status.FullyQualifiedName
}

func (rap *RowAccessPolicy) GetProviderRef() ProviderReference {
	return rap.Spec.ProviderRef
}

func (rap *RowAccessPolicy) GetSpecName() string {
	return rap.Spec.Name
}

func (rap *RowAccessPolicy) GetUseRole() *string {
	return rap.Spec.UseRole
}

func (rap *RowAccessPolicy) GetPaused() bool {
	return rap.Spec.Paused
}

func (rap *RowAccessPolicy) GetManagementPolicies() ManagementPolicies {
	return rap.Spec.ManagementPolicies
}

func (rap *RowAccessPolicy) SetCreateOrAlter(val *bool) {
	rap.Spec.ManagementPolicies.CreateOrAlter = val
}

func (rap *RowAccessPolicy) GetObservedGeneration() int64 {
	return rap.Status.ObservedGeneration
}

func (rap *RowAccessPolicy) SetObservedGeneration(val int64) {
	rap.Status.ObservedGeneration = val
}

func (rap *RowAccessPolicy) GetLastAppliedSpecHash() string {
	return rap.Status.LastAppliedSpecHash
}

func (rap *RowAccessPolicy) SetLastAppliedSpecHash(val string) {
	rap.Status.LastAppliedSpecHash = val
}

func (rap *RowAccessPolicy) ValidateSpec() error {
	return rap.Spec.Validate()
}

func (rap *RowAccessPolicy) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(rap.Spec)
}

func (rap *RowAccessPolicy) GetOwner() string {
	if rap.Status.ShowOutput != nil {
		return rap.Status.ShowOutput.Owner
	}

	return ""
}

func (rap *RowAccessPolicy) GetTrackedParametersList() []string {
	return rap.Status.TrackedParameters
}

func (rap *RowAccessPolicy) SetTrackedParametersList(val []string) {
	rap.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// Stage
// ---------------------------------------------------------------------------

func (s *Stage) GetConditions() []metav1.Condition {
	return s.Status.Conditions
}

func (s *Stage) SetConditions(conditions []metav1.Condition) {
	s.Status.Conditions = conditions
}

func (s *Stage) GetDeletionPolicy() DeletionPolicy {
	if s.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return s.Spec.DeletionPolicy
}

func (s *Stage) GetFullyQualifiedName() string {
	return s.Status.FullyQualifiedName
}

func (s *Stage) GetProviderRef() ProviderReference {
	return s.Spec.ProviderRef
}

func (s *Stage) GetSpecName() string {
	return s.Spec.Name
}

func (s *Stage) GetUseRole() *string {
	return s.Spec.UseRole
}

func (s *Stage) GetPaused() bool {
	return s.Spec.Paused
}

func (s *Stage) GetManagementPolicies() ManagementPolicies {
	return s.Spec.ManagementPolicies
}

func (s *Stage) SetCreateOrAlter(val *bool) {
	s.Spec.ManagementPolicies.CreateOrAlter = val
}

func (s *Stage) GetObservedGeneration() int64 {
	return s.Status.ObservedGeneration
}

func (s *Stage) SetObservedGeneration(val int64) {
	s.Status.ObservedGeneration = val
}

func (s *Stage) GetLastAppliedSpecHash() string {
	return s.Status.LastAppliedSpecHash
}

func (s *Stage) SetLastAppliedSpecHash(val string) {
	s.Status.LastAppliedSpecHash = val
}

func (s *Stage) ValidateSpec() error {
	return s.Spec.Validate()
}

func (s *Stage) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(s.Spec)
}

func (s *Stage) GetOwner() string {
	if s.Status.ShowOutput != nil {
		return s.Status.ShowOutput.Owner
	}

	return ""
}

func (s *Stage) GetTrackedParametersList() []string {
	return s.Status.TrackedParameters
}

func (s *Stage) SetTrackedParametersList(val []string) {
	s.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// StreamOnTable
// ---------------------------------------------------------------------------

func (s *StreamOnTable) GetConditions() []metav1.Condition {
	return s.Status.Conditions
}

func (s *StreamOnTable) SetConditions(conditions []metav1.Condition) {
	s.Status.Conditions = conditions
}

func (s *StreamOnTable) GetDeletionPolicy() DeletionPolicy {
	if s.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return s.Spec.DeletionPolicy
}

func (s *StreamOnTable) GetFullyQualifiedName() string {
	return s.Status.FullyQualifiedName
}

func (s *StreamOnTable) GetProviderRef() ProviderReference {
	return s.Spec.ProviderRef
}

func (s *StreamOnTable) GetSpecName() string {
	return s.Spec.Name
}

func (s *StreamOnTable) GetUseRole() *string {
	return s.Spec.UseRole
}

func (s *StreamOnTable) GetPaused() bool {
	return s.Spec.Paused
}

func (s *StreamOnTable) GetManagementPolicies() ManagementPolicies {
	return s.Spec.ManagementPolicies
}

func (s *StreamOnTable) SetCreateOrAlter(val *bool) {
	s.Spec.ManagementPolicies.CreateOrAlter = val
}

func (s *StreamOnTable) GetObservedGeneration() int64 {
	return s.Status.ObservedGeneration
}

func (s *StreamOnTable) SetObservedGeneration(val int64) {
	s.Status.ObservedGeneration = val
}

func (s *StreamOnTable) GetLastAppliedSpecHash() string {
	return s.Status.LastAppliedSpecHash
}

func (s *StreamOnTable) SetLastAppliedSpecHash(val string) {
	s.Status.LastAppliedSpecHash = val
}

func (s *StreamOnTable) ValidateSpec() error {
	return s.Spec.Validate()
}

func (s *StreamOnTable) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(s.Spec)
}

func (s *StreamOnTable) GetOwner() string {
	if s.Status.ShowOutput != nil {
		return s.Status.ShowOutput.Owner
	}

	return ""
}

func (s *StreamOnTable) GetTrackedParametersList() []string {
	return s.Status.TrackedParameters
}

func (s *StreamOnTable) SetTrackedParametersList(val []string) {
	s.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// StreamOnView
// ---------------------------------------------------------------------------

func (s *StreamOnView) GetConditions() []metav1.Condition {
	return s.Status.Conditions
}

func (s *StreamOnView) SetConditions(conditions []metav1.Condition) {
	s.Status.Conditions = conditions
}

func (s *StreamOnView) GetDeletionPolicy() DeletionPolicy {
	if s.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return s.Spec.DeletionPolicy
}

func (s *StreamOnView) GetFullyQualifiedName() string {
	return s.Status.FullyQualifiedName
}

func (s *StreamOnView) GetProviderRef() ProviderReference {
	return s.Spec.ProviderRef
}

func (s *StreamOnView) GetSpecName() string {
	return s.Spec.Name
}

func (s *StreamOnView) GetUseRole() *string {
	return s.Spec.UseRole
}

func (s *StreamOnView) GetPaused() bool {
	return s.Spec.Paused
}

func (s *StreamOnView) GetManagementPolicies() ManagementPolicies {
	return s.Spec.ManagementPolicies
}

func (s *StreamOnView) SetCreateOrAlter(val *bool) {
	s.Spec.ManagementPolicies.CreateOrAlter = val
}

func (s *StreamOnView) GetObservedGeneration() int64 {
	return s.Status.ObservedGeneration
}

func (s *StreamOnView) SetObservedGeneration(val int64) {
	s.Status.ObservedGeneration = val
}

func (s *StreamOnView) GetLastAppliedSpecHash() string {
	return s.Status.LastAppliedSpecHash
}

func (s *StreamOnView) SetLastAppliedSpecHash(val string) {
	s.Status.LastAppliedSpecHash = val
}

func (s *StreamOnView) ValidateSpec() error {
	return s.Spec.Validate()
}

func (s *StreamOnView) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(s.Spec)
}

func (s *StreamOnView) GetOwner() string {
	if s.Status.ShowOutput != nil {
		return s.Status.ShowOutput.Owner
	}

	return ""
}

func (s *StreamOnView) GetTrackedParametersList() []string {
	return s.Status.TrackedParameters
}

func (s *StreamOnView) SetTrackedParametersList(val []string) {
	s.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// StreamOnExternalTable
// ---------------------------------------------------------------------------

func (s *StreamOnExternalTable) GetConditions() []metav1.Condition {
	return s.Status.Conditions
}

func (s *StreamOnExternalTable) SetConditions(conditions []metav1.Condition) {
	s.Status.Conditions = conditions
}

func (s *StreamOnExternalTable) GetDeletionPolicy() DeletionPolicy {
	if s.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return s.Spec.DeletionPolicy
}

func (s *StreamOnExternalTable) GetFullyQualifiedName() string {
	return s.Status.FullyQualifiedName
}

func (s *StreamOnExternalTable) GetProviderRef() ProviderReference {
	return s.Spec.ProviderRef
}

func (s *StreamOnExternalTable) GetSpecName() string {
	return s.Spec.Name
}

func (s *StreamOnExternalTable) GetUseRole() *string {
	return s.Spec.UseRole
}

func (s *StreamOnExternalTable) GetPaused() bool {
	return s.Spec.Paused
}

func (s *StreamOnExternalTable) GetManagementPolicies() ManagementPolicies {
	return s.Spec.ManagementPolicies
}

func (s *StreamOnExternalTable) SetCreateOrAlter(val *bool) {
	s.Spec.ManagementPolicies.CreateOrAlter = val
}

func (s *StreamOnExternalTable) GetObservedGeneration() int64 {
	return s.Status.ObservedGeneration
}

func (s *StreamOnExternalTable) SetObservedGeneration(val int64) {
	s.Status.ObservedGeneration = val
}

func (s *StreamOnExternalTable) GetLastAppliedSpecHash() string {
	return s.Status.LastAppliedSpecHash
}

func (s *StreamOnExternalTable) SetLastAppliedSpecHash(val string) {
	s.Status.LastAppliedSpecHash = val
}

func (s *StreamOnExternalTable) ValidateSpec() error {
	return s.Spec.Validate()
}

func (s *StreamOnExternalTable) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(s.Spec)
}

func (s *StreamOnExternalTable) GetOwner() string {
	if s.Status.ShowOutput != nil {
		return s.Status.ShowOutput.Owner
	}

	return ""
}

func (s *StreamOnExternalTable) GetTrackedParametersList() []string {
	return s.Status.TrackedParameters
}

func (s *StreamOnExternalTable) SetTrackedParametersList(val []string) {
	s.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// StreamOnDirectoryTable
// ---------------------------------------------------------------------------

func (s *StreamOnDirectoryTable) GetConditions() []metav1.Condition {
	return s.Status.Conditions
}

func (s *StreamOnDirectoryTable) SetConditions(conditions []metav1.Condition) {
	s.Status.Conditions = conditions
}

func (s *StreamOnDirectoryTable) GetDeletionPolicy() DeletionPolicy {
	if s.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return s.Spec.DeletionPolicy
}

func (s *StreamOnDirectoryTable) GetFullyQualifiedName() string {
	return s.Status.FullyQualifiedName
}

func (s *StreamOnDirectoryTable) GetProviderRef() ProviderReference {
	return s.Spec.ProviderRef
}

func (s *StreamOnDirectoryTable) GetSpecName() string {
	return s.Spec.Name
}

func (s *StreamOnDirectoryTable) GetUseRole() *string {
	return s.Spec.UseRole
}

func (s *StreamOnDirectoryTable) GetPaused() bool {
	return s.Spec.Paused
}

func (s *StreamOnDirectoryTable) GetManagementPolicies() ManagementPolicies {
	return s.Spec.ManagementPolicies
}

func (s *StreamOnDirectoryTable) SetCreateOrAlter(val *bool) {
	s.Spec.ManagementPolicies.CreateOrAlter = val
}

func (s *StreamOnDirectoryTable) GetObservedGeneration() int64 {
	return s.Status.ObservedGeneration
}

func (s *StreamOnDirectoryTable) SetObservedGeneration(val int64) {
	s.Status.ObservedGeneration = val
}

func (s *StreamOnDirectoryTable) GetLastAppliedSpecHash() string {
	return s.Status.LastAppliedSpecHash
}

func (s *StreamOnDirectoryTable) SetLastAppliedSpecHash(val string) {
	s.Status.LastAppliedSpecHash = val
}

func (s *StreamOnDirectoryTable) ValidateSpec() error {
	return s.Spec.Validate()
}

func (s *StreamOnDirectoryTable) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(s.Spec)
}

func (s *StreamOnDirectoryTable) GetOwner() string {
	if s.Status.ShowOutput != nil {
		return s.Status.ShowOutput.Owner
	}

	return ""
}

func (s *StreamOnDirectoryTable) GetTrackedParametersList() []string {
	return s.Status.TrackedParameters
}

func (s *StreamOnDirectoryTable) SetTrackedParametersList(val []string) {
	s.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// StreamOnDynamicTable
// ---------------------------------------------------------------------------

func (s *StreamOnDynamicTable) GetConditions() []metav1.Condition {
	return s.Status.Conditions
}

func (s *StreamOnDynamicTable) SetConditions(conditions []metav1.Condition) {
	s.Status.Conditions = conditions
}

func (s *StreamOnDynamicTable) GetDeletionPolicy() DeletionPolicy {
	if s.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return s.Spec.DeletionPolicy
}

func (s *StreamOnDynamicTable) GetFullyQualifiedName() string {
	return s.Status.FullyQualifiedName
}

func (s *StreamOnDynamicTable) GetProviderRef() ProviderReference {
	return s.Spec.ProviderRef
}

func (s *StreamOnDynamicTable) GetSpecName() string {
	return s.Spec.Name
}

func (s *StreamOnDynamicTable) GetUseRole() *string {
	return s.Spec.UseRole
}

func (s *StreamOnDynamicTable) GetPaused() bool {
	return s.Spec.Paused
}

func (s *StreamOnDynamicTable) GetManagementPolicies() ManagementPolicies {
	return s.Spec.ManagementPolicies
}

func (s *StreamOnDynamicTable) SetCreateOrAlter(val *bool) {
	s.Spec.ManagementPolicies.CreateOrAlter = val
}

func (s *StreamOnDynamicTable) GetObservedGeneration() int64 {
	return s.Status.ObservedGeneration
}

func (s *StreamOnDynamicTable) SetObservedGeneration(val int64) {
	s.Status.ObservedGeneration = val
}

func (s *StreamOnDynamicTable) GetLastAppliedSpecHash() string {
	return s.Status.LastAppliedSpecHash
}

func (s *StreamOnDynamicTable) SetLastAppliedSpecHash(val string) {
	s.Status.LastAppliedSpecHash = val
}

func (s *StreamOnDynamicTable) ValidateSpec() error {
	return s.Spec.Validate()
}

func (s *StreamOnDynamicTable) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(s.Spec)
}

func (s *StreamOnDynamicTable) GetOwner() string {
	if s.Status.ShowOutput != nil {
		return s.Status.ShowOutput.Owner
	}

	return ""
}

func (s *StreamOnDynamicTable) GetTrackedParametersList() []string {
	return s.Status.TrackedParameters
}

func (s *StreamOnDynamicTable) SetTrackedParametersList(val []string) {
	s.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// Task
// ---------------------------------------------------------------------------

func (t *Task) GetConditions() []metav1.Condition {
	return t.Status.Conditions
}

func (t *Task) SetConditions(conditions []metav1.Condition) {
	t.Status.Conditions = conditions
}

func (t *Task) GetDeletionPolicy() DeletionPolicy {
	if t.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return t.Spec.DeletionPolicy
}

func (t *Task) GetFullyQualifiedName() string {
	return t.Status.FullyQualifiedName
}

func (t *Task) GetProviderRef() ProviderReference {
	return t.Spec.ProviderRef
}

func (t *Task) GetSpecName() string {
	return t.Spec.Name
}

func (t *Task) GetUseRole() *string {
	return t.Spec.UseRole
}

func (t *Task) GetPaused() bool {
	return t.Spec.Paused
}

func (t *Task) GetManagementPolicies() ManagementPolicies {
	return t.Spec.ManagementPolicies
}

func (t *Task) SetCreateOrAlter(val *bool) {
	t.Spec.ManagementPolicies.CreateOrAlter = val
}

func (t *Task) GetObservedGeneration() int64 {
	return t.Status.ObservedGeneration
}

func (t *Task) SetObservedGeneration(val int64) {
	t.Status.ObservedGeneration = val
}

func (t *Task) GetLastAppliedSpecHash() string {
	return t.Status.LastAppliedSpecHash
}

func (t *Task) SetLastAppliedSpecHash(val string) {
	t.Status.LastAppliedSpecHash = val
}

func (t *Task) ValidateSpec() error {
	return t.Spec.Validate()
}

func (t *Task) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(t.Spec)
}

func (t *Task) GetOwner() string {
	if t.Status.ShowOutput != nil {
		return t.Status.ShowOutput.Owner
	}

	return ""
}

func (t *Task) GetTrackedParametersList() []string {
	return t.Status.TrackedParameters
}

func (t *Task) SetTrackedParametersList(val []string) {
	t.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// Alert
// ---------------------------------------------------------------------------

func (a *Alert) GetConditions() []metav1.Condition {
	return a.Status.Conditions
}

func (a *Alert) SetConditions(conditions []metav1.Condition) {
	a.Status.Conditions = conditions
}

func (a *Alert) GetDeletionPolicy() DeletionPolicy {
	if a.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return a.Spec.DeletionPolicy
}

func (a *Alert) GetFullyQualifiedName() string {
	return a.Status.FullyQualifiedName
}

func (a *Alert) GetProviderRef() ProviderReference {
	return a.Spec.ProviderRef
}

func (a *Alert) GetSpecName() string {
	return a.Spec.Name
}

func (a *Alert) GetUseRole() *string {
	return a.Spec.UseRole
}

func (a *Alert) GetPaused() bool {
	return a.Spec.Paused
}

func (a *Alert) GetManagementPolicies() ManagementPolicies {
	return a.Spec.ManagementPolicies
}

func (a *Alert) SetCreateOrAlter(val *bool) {
	a.Spec.ManagementPolicies.CreateOrAlter = val
}

func (a *Alert) GetObservedGeneration() int64 {
	return a.Status.ObservedGeneration
}

func (a *Alert) SetObservedGeneration(val int64) {
	a.Status.ObservedGeneration = val
}

func (a *Alert) GetLastAppliedSpecHash() string {
	return a.Status.LastAppliedSpecHash
}

func (a *Alert) SetLastAppliedSpecHash(val string) {
	a.Status.LastAppliedSpecHash = val
}

func (a *Alert) ValidateSpec() error {
	return a.Spec.Validate()
}

func (a *Alert) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(a.Spec)
}

func (a *Alert) GetOwner() string {
	if a.Status.ShowOutput != nil {
		return a.Status.ShowOutput.Owner
	}

	return ""
}

func (a *Alert) GetTrackedParametersList() []string {
	return a.Status.TrackedParameters
}

func (a *Alert) SetTrackedParametersList(val []string) {
	a.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// View
// ---------------------------------------------------------------------------

func (v *View) GetConditions() []metav1.Condition {
	return v.Status.Conditions
}

func (v *View) SetConditions(conditions []metav1.Condition) {
	v.Status.Conditions = conditions
}

func (v *View) GetDeletionPolicy() DeletionPolicy {
	if v.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return v.Spec.DeletionPolicy
}

func (v *View) GetFullyQualifiedName() string {
	return v.Status.FullyQualifiedName
}

func (v *View) GetProviderRef() ProviderReference {
	return v.Spec.ProviderRef
}

func (v *View) GetSpecName() string {
	return v.Spec.Name
}

func (v *View) GetUseRole() *string {
	return v.Spec.UseRole
}

func (v *View) GetPaused() bool {
	return v.Spec.Paused
}

func (v *View) GetManagementPolicies() ManagementPolicies {
	return v.Spec.ManagementPolicies
}

func (v *View) SetCreateOrAlter(val *bool) {
	v.Spec.ManagementPolicies.CreateOrAlter = val
}

func (v *View) GetObservedGeneration() int64 {
	return v.Status.ObservedGeneration
}

func (v *View) SetObservedGeneration(val int64) {
	v.Status.ObservedGeneration = val
}

func (v *View) GetLastAppliedSpecHash() string {
	return v.Status.LastAppliedSpecHash
}

func (v *View) SetLastAppliedSpecHash(val string) {
	v.Status.LastAppliedSpecHash = val
}

func (v *View) ValidateSpec() error {
	return v.Spec.Validate()
}

func (v *View) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(v.Spec)
}

func (v *View) GetOwner() string {
	if v.Status.ShowOutput != nil {
		return v.Status.ShowOutput.Owner
	}

	return ""
}

func (v *View) GetTrackedParametersList() []string {
	return v.Status.TrackedParameters
}

func (v *View) SetTrackedParametersList(val []string) {
	v.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// Table
// ---------------------------------------------------------------------------

func (t *Table) GetConditions() []metav1.Condition {
	return t.Status.Conditions
}

func (t *Table) SetConditions(conditions []metav1.Condition) {
	t.Status.Conditions = conditions
}

func (t *Table) GetDeletionPolicy() DeletionPolicy {
	if t.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return t.Spec.DeletionPolicy
}

func (t *Table) GetFullyQualifiedName() string {
	return t.Status.FullyQualifiedName
}

func (t *Table) GetProviderRef() ProviderReference {
	return t.Spec.ProviderRef
}

func (t *Table) GetSpecName() string {
	return t.Spec.Name
}

func (t *Table) GetUseRole() *string {
	return t.Spec.UseRole
}

func (t *Table) GetPaused() bool {
	return t.Spec.Paused
}

func (t *Table) GetManagementPolicies() ManagementPolicies {
	return t.Spec.ManagementPolicies
}

func (t *Table) SetCreateOrAlter(val *bool) {
	t.Spec.ManagementPolicies.CreateOrAlter = val
}

func (t *Table) GetObservedGeneration() int64 {
	return t.Status.ObservedGeneration
}

func (t *Table) SetObservedGeneration(val int64) {
	t.Status.ObservedGeneration = val
}

func (t *Table) GetLastAppliedSpecHash() string {
	return t.Status.LastAppliedSpecHash
}

func (t *Table) SetLastAppliedSpecHash(val string) {
	t.Status.LastAppliedSpecHash = val
}

func (t *Table) ValidateSpec() error {
	return t.Spec.Validate()
}

func (t *Table) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(t.Spec)
}

func (t *Table) GetOwner() string {
	if t.Status.ShowOutput != nil {
		return t.Status.ShowOutput.Owner
	}

	return ""
}

func (t *Table) GetTrackedParametersList() []string {
	return t.Status.TrackedParameters
}

func (t *Table) SetTrackedParametersList(val []string) {
	t.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// NetworkPolicy
// ---------------------------------------------------------------------------

func (np *NetworkPolicy) GetConditions() []metav1.Condition {
	return np.Status.Conditions
}

func (np *NetworkPolicy) SetConditions(conditions []metav1.Condition) {
	np.Status.Conditions = conditions
}

func (np *NetworkPolicy) GetDeletionPolicy() DeletionPolicy {
	if np.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return np.Spec.DeletionPolicy
}

func (np *NetworkPolicy) GetFullyQualifiedName() string {
	return np.Status.FullyQualifiedName
}

func (np *NetworkPolicy) GetProviderRef() ProviderReference {
	return np.Spec.ProviderRef
}

func (np *NetworkPolicy) GetSpecName() string {
	return np.Spec.Name
}

func (np *NetworkPolicy) GetUseRole() *string {
	return np.Spec.UseRole
}

func (np *NetworkPolicy) GetPaused() bool {
	return np.Spec.Paused
}

func (np *NetworkPolicy) GetManagementPolicies() ManagementPolicies {
	return np.Spec.ManagementPolicies
}

func (np *NetworkPolicy) SetCreateOrAlter(val *bool) {
	np.Spec.ManagementPolicies.CreateOrAlter = val
}

func (np *NetworkPolicy) GetObservedGeneration() int64 {
	return np.Status.ObservedGeneration
}

func (np *NetworkPolicy) SetObservedGeneration(val int64) {
	np.Status.ObservedGeneration = val
}

func (np *NetworkPolicy) GetLastAppliedSpecHash() string {
	return np.Status.LastAppliedSpecHash
}

func (np *NetworkPolicy) SetLastAppliedSpecHash(val string) {
	np.Status.LastAppliedSpecHash = val
}

func (np *NetworkPolicy) ValidateSpec() error {
	return np.Spec.Validate()
}

func (np *NetworkPolicy) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(np.Spec)
}

func (np *NetworkPolicy) GetOwner() string {
	// SHOW NETWORK POLICIES does not return an owner column.
	return ""
}

func (np *NetworkPolicy) GetTrackedParametersList() []string {
	return np.Status.TrackedParameters
}

func (np *NetworkPolicy) SetTrackedParametersList(val []string) {
	np.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// ResourceMonitor
// ---------------------------------------------------------------------------

func (rm *ResourceMonitor) GetConditions() []metav1.Condition {
	return rm.Status.Conditions
}

func (rm *ResourceMonitor) SetConditions(conditions []metav1.Condition) {
	rm.Status.Conditions = conditions
}

func (rm *ResourceMonitor) GetDeletionPolicy() DeletionPolicy {
	if rm.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return rm.Spec.DeletionPolicy
}

func (rm *ResourceMonitor) GetFullyQualifiedName() string {
	return rm.Status.FullyQualifiedName
}

func (rm *ResourceMonitor) GetProviderRef() ProviderReference {
	return rm.Spec.ProviderRef
}

func (rm *ResourceMonitor) GetSpecName() string {
	return rm.Spec.Name
}

func (rm *ResourceMonitor) GetUseRole() *string {
	return rm.Spec.UseRole
}

func (rm *ResourceMonitor) GetPaused() bool {
	return rm.Spec.Paused
}

func (rm *ResourceMonitor) GetManagementPolicies() ManagementPolicies {
	return rm.Spec.ManagementPolicies
}

func (rm *ResourceMonitor) SetCreateOrAlter(val *bool) {
	rm.Spec.ManagementPolicies.CreateOrAlter = val
}

func (rm *ResourceMonitor) GetObservedGeneration() int64 {
	return rm.Status.ObservedGeneration
}

func (rm *ResourceMonitor) SetObservedGeneration(val int64) {
	rm.Status.ObservedGeneration = val
}

func (rm *ResourceMonitor) GetLastAppliedSpecHash() string {
	return rm.Status.LastAppliedSpecHash
}

func (rm *ResourceMonitor) SetLastAppliedSpecHash(val string) {
	rm.Status.LastAppliedSpecHash = val
}

func (rm *ResourceMonitor) ValidateSpec() error {
	return rm.Spec.Validate()
}

func (rm *ResourceMonitor) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(rm.Spec)
}

func (rm *ResourceMonitor) GetOwner() string {
	// SHOW RESOURCE MONITORS does not return an owner column.
	return ""
}

func (rm *ResourceMonitor) GetTrackedParametersList() []string {
	return rm.Status.TrackedParameters
}

func (rm *ResourceMonitor) SetTrackedParametersList(val []string) {
	rm.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// StorageIntegration
// ---------------------------------------------------------------------------

func (si *StorageIntegration) GetConditions() []metav1.Condition {
	return si.Status.Conditions
}

func (si *StorageIntegration) SetConditions(conditions []metav1.Condition) {
	si.Status.Conditions = conditions
}

func (si *StorageIntegration) GetDeletionPolicy() DeletionPolicy {
	if si.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return si.Spec.DeletionPolicy
}

func (si *StorageIntegration) GetFullyQualifiedName() string {
	return si.Status.FullyQualifiedName
}

func (si *StorageIntegration) GetProviderRef() ProviderReference {
	return si.Spec.ProviderRef
}

func (si *StorageIntegration) GetSpecName() string {
	return si.Spec.Name
}

func (si *StorageIntegration) GetUseRole() *string {
	return si.Spec.UseRole
}

func (si *StorageIntegration) GetPaused() bool {
	return si.Spec.Paused
}

func (si *StorageIntegration) GetManagementPolicies() ManagementPolicies {
	return si.Spec.ManagementPolicies
}

func (si *StorageIntegration) SetCreateOrAlter(val *bool) {
	si.Spec.ManagementPolicies.CreateOrAlter = val
}

func (si *StorageIntegration) GetObservedGeneration() int64 {
	return si.Status.ObservedGeneration
}

func (si *StorageIntegration) SetObservedGeneration(val int64) {
	si.Status.ObservedGeneration = val
}

func (si *StorageIntegration) GetLastAppliedSpecHash() string {
	return si.Status.LastAppliedSpecHash
}

func (si *StorageIntegration) SetLastAppliedSpecHash(val string) {
	si.Status.LastAppliedSpecHash = val
}

func (si *StorageIntegration) ValidateSpec() error {
	return si.Spec.Validate()
}

func (si *StorageIntegration) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(si.Spec)
}

func (si *StorageIntegration) GetOwner() string {
	// SHOW STORAGE INTEGRATIONS does not return an owner column.
	return ""
}

func (si *StorageIntegration) GetTrackedParametersList() []string {
	return si.Status.TrackedParameters
}

func (si *StorageIntegration) SetTrackedParametersList(val []string) {
	si.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// FileFormat
// ---------------------------------------------------------------------------

func (ff *FileFormat) GetConditions() []metav1.Condition {
	return ff.Status.Conditions
}

func (ff *FileFormat) SetConditions(conditions []metav1.Condition) {
	ff.Status.Conditions = conditions
}

func (ff *FileFormat) GetDeletionPolicy() DeletionPolicy {
	if ff.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return ff.Spec.DeletionPolicy
}

func (ff *FileFormat) GetFullyQualifiedName() string {
	return ff.Status.FullyQualifiedName
}

func (ff *FileFormat) GetProviderRef() ProviderReference {
	return ff.Spec.ProviderRef
}

func (ff *FileFormat) GetSpecName() string {
	return ff.Spec.Name
}

func (ff *FileFormat) GetUseRole() *string {
	return ff.Spec.UseRole
}

func (ff *FileFormat) GetPaused() bool {
	return ff.Spec.Paused
}

func (ff *FileFormat) GetManagementPolicies() ManagementPolicies {
	return ff.Spec.ManagementPolicies
}

func (ff *FileFormat) SetCreateOrAlter(val *bool) {
	ff.Spec.ManagementPolicies.CreateOrAlter = val
}

func (ff *FileFormat) GetObservedGeneration() int64 {
	return ff.Status.ObservedGeneration
}

func (ff *FileFormat) SetObservedGeneration(val int64) {
	ff.Status.ObservedGeneration = val
}

func (ff *FileFormat) GetLastAppliedSpecHash() string {
	return ff.Status.LastAppliedSpecHash
}

func (ff *FileFormat) SetLastAppliedSpecHash(val string) {
	ff.Status.LastAppliedSpecHash = val
}

func (ff *FileFormat) ValidateSpec() error {
	return ff.Spec.Validate()
}

func (ff *FileFormat) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(ff.Spec)
}

func (ff *FileFormat) GetOwner() string {
	if ff.Status.ShowOutput != nil {
		return ff.Status.ShowOutput.Owner
	}

	return ""
}

func (ff *FileFormat) GetTrackedParametersList() []string {
	return ff.Status.TrackedParameters
}

func (ff *FileFormat) SetTrackedParametersList(val []string) {
	ff.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// Pipe
// ---------------------------------------------------------------------------

func (p *Pipe) GetConditions() []metav1.Condition {
	return p.Status.Conditions
}

func (p *Pipe) SetConditions(conditions []metav1.Condition) {
	p.Status.Conditions = conditions
}

func (p *Pipe) GetDeletionPolicy() DeletionPolicy {
	if p.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return p.Spec.DeletionPolicy
}

func (p *Pipe) GetFullyQualifiedName() string {
	return p.Status.FullyQualifiedName
}

func (p *Pipe) GetProviderRef() ProviderReference {
	return p.Spec.ProviderRef
}

func (p *Pipe) GetSpecName() string {
	return p.Spec.Name
}

func (p *Pipe) GetUseRole() *string {
	return p.Spec.UseRole
}

func (p *Pipe) GetPaused() bool {
	return p.Spec.Paused
}

func (p *Pipe) GetManagementPolicies() ManagementPolicies {
	return p.Spec.ManagementPolicies
}

func (p *Pipe) SetCreateOrAlter(val *bool) {
	p.Spec.ManagementPolicies.CreateOrAlter = val
}

func (p *Pipe) GetObservedGeneration() int64 {
	return p.Status.ObservedGeneration
}

func (p *Pipe) SetObservedGeneration(val int64) {
	p.Status.ObservedGeneration = val
}

func (p *Pipe) GetLastAppliedSpecHash() string {
	return p.Status.LastAppliedSpecHash
}

func (p *Pipe) SetLastAppliedSpecHash(val string) {
	p.Status.LastAppliedSpecHash = val
}

func (p *Pipe) ValidateSpec() error {
	return p.Spec.Validate()
}

func (p *Pipe) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(p.Spec)
}

func (p *Pipe) GetOwner() string {
	if p.Status.ShowOutput != nil {
		return p.Status.ShowOutput.Owner
	}

	return ""
}

func (p *Pipe) GetTrackedParametersList() []string {
	return p.Status.TrackedParameters
}

func (p *Pipe) SetTrackedParametersList(val []string) {
	p.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// DynamicTable
// ---------------------------------------------------------------------------

func (dt *DynamicTable) GetConditions() []metav1.Condition {
	return dt.Status.Conditions
}

func (dt *DynamicTable) SetConditions(conditions []metav1.Condition) {
	dt.Status.Conditions = conditions
}

func (dt *DynamicTable) GetDeletionPolicy() DeletionPolicy {
	if dt.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return dt.Spec.DeletionPolicy
}

func (dt *DynamicTable) GetFullyQualifiedName() string {
	return dt.Status.FullyQualifiedName
}

func (dt *DynamicTable) GetProviderRef() ProviderReference {
	return dt.Spec.ProviderRef
}

func (dt *DynamicTable) GetSpecName() string {
	return dt.Spec.Name
}

func (dt *DynamicTable) GetUseRole() *string {
	return dt.Spec.UseRole
}

func (dt *DynamicTable) GetPaused() bool {
	return dt.Spec.Paused
}

func (dt *DynamicTable) GetManagementPolicies() ManagementPolicies {
	return dt.Spec.ManagementPolicies
}

func (dt *DynamicTable) SetCreateOrAlter(val *bool) {
	dt.Spec.ManagementPolicies.CreateOrAlter = val
}

func (dt *DynamicTable) GetObservedGeneration() int64 {
	return dt.Status.ObservedGeneration
}

func (dt *DynamicTable) SetObservedGeneration(val int64) {
	dt.Status.ObservedGeneration = val
}

func (dt *DynamicTable) GetLastAppliedSpecHash() string {
	return dt.Status.LastAppliedSpecHash
}

func (dt *DynamicTable) SetLastAppliedSpecHash(val string) {
	dt.Status.LastAppliedSpecHash = val
}

func (dt *DynamicTable) ValidateSpec() error {
	return dt.Spec.Validate()
}

func (dt *DynamicTable) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(dt.Spec)
}

func (dt *DynamicTable) GetOwner() string {
	if dt.Status.ShowOutput != nil {
		return dt.Status.ShowOutput.Owner
	}

	return ""
}

func (dt *DynamicTable) GetTrackedParametersList() []string {
	return dt.Status.TrackedParameters
}

func (dt *DynamicTable) SetTrackedParametersList(val []string) {
	dt.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// NotificationIntegration
// ---------------------------------------------------------------------------

func (ni *NotificationIntegration) GetConditions() []metav1.Condition {
	return ni.Status.Conditions
}

func (ni *NotificationIntegration) SetConditions(conditions []metav1.Condition) {
	ni.Status.Conditions = conditions
}

func (ni *NotificationIntegration) GetDeletionPolicy() DeletionPolicy {
	if ni.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return ni.Spec.DeletionPolicy
}

func (ni *NotificationIntegration) GetFullyQualifiedName() string {
	return ni.Status.FullyQualifiedName
}

func (ni *NotificationIntegration) GetProviderRef() ProviderReference {
	return ni.Spec.ProviderRef
}

func (ni *NotificationIntegration) GetSpecName() string {
	return ni.Spec.Name
}

func (ni *NotificationIntegration) GetUseRole() *string {
	return ni.Spec.UseRole
}

func (ni *NotificationIntegration) GetPaused() bool {
	return ni.Spec.Paused
}

func (ni *NotificationIntegration) GetManagementPolicies() ManagementPolicies {
	return ni.Spec.ManagementPolicies
}

func (ni *NotificationIntegration) SetCreateOrAlter(val *bool) {
	ni.Spec.ManagementPolicies.CreateOrAlter = val
}

func (ni *NotificationIntegration) GetObservedGeneration() int64 {
	return ni.Status.ObservedGeneration
}

func (ni *NotificationIntegration) SetObservedGeneration(val int64) {
	ni.Status.ObservedGeneration = val
}

func (ni *NotificationIntegration) GetLastAppliedSpecHash() string {
	return ni.Status.LastAppliedSpecHash
}

func (ni *NotificationIntegration) SetLastAppliedSpecHash(val string) {
	ni.Status.LastAppliedSpecHash = val
}

func (ni *NotificationIntegration) ValidateSpec() error {
	return ni.Spec.Validate()
}

func (ni *NotificationIntegration) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(ni.Spec)
}

func (ni *NotificationIntegration) GetOwner() string {
	// SHOW NOTIFICATION INTEGRATIONS does not return an owner column.
	return ""
}

func (ni *NotificationIntegration) GetTrackedParametersList() []string {
	return ni.Status.TrackedParameters
}

func (ni *NotificationIntegration) SetTrackedParametersList(val []string) {
	ni.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// SecurityIntegration
// ---------------------------------------------------------------------------

func (si *SecurityIntegration) GetConditions() []metav1.Condition {
	return si.Status.Conditions
}

func (si *SecurityIntegration) SetConditions(conditions []metav1.Condition) {
	si.Status.Conditions = conditions
}

func (si *SecurityIntegration) GetDeletionPolicy() DeletionPolicy {
	if si.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return si.Spec.DeletionPolicy
}

func (si *SecurityIntegration) GetFullyQualifiedName() string {
	return si.Status.FullyQualifiedName
}

func (si *SecurityIntegration) GetProviderRef() ProviderReference {
	return si.Spec.ProviderRef
}

func (si *SecurityIntegration) GetSpecName() string {
	return si.Spec.Name
}

func (si *SecurityIntegration) GetUseRole() *string {
	return si.Spec.UseRole
}

func (si *SecurityIntegration) GetPaused() bool {
	return si.Spec.Paused
}

func (si *SecurityIntegration) GetManagementPolicies() ManagementPolicies {
	return si.Spec.ManagementPolicies
}

func (si *SecurityIntegration) SetCreateOrAlter(val *bool) {
	si.Spec.ManagementPolicies.CreateOrAlter = val
}

func (si *SecurityIntegration) GetObservedGeneration() int64 {
	return si.Status.ObservedGeneration
}

func (si *SecurityIntegration) SetObservedGeneration(val int64) {
	si.Status.ObservedGeneration = val
}

func (si *SecurityIntegration) GetLastAppliedSpecHash() string {
	return si.Status.LastAppliedSpecHash
}

func (si *SecurityIntegration) SetLastAppliedSpecHash(val string) {
	si.Status.LastAppliedSpecHash = val
}

func (si *SecurityIntegration) ValidateSpec() error {
	return si.Spec.Validate()
}

func (si *SecurityIntegration) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(si.Spec)
}

func (si *SecurityIntegration) GetOwner() string {
	// SHOW SECURITY INTEGRATIONS does not return an owner column.
	return ""
}

func (si *SecurityIntegration) GetTrackedParametersList() []string {
	return si.Status.TrackedParameters
}

func (si *SecurityIntegration) SetTrackedParametersList(val []string) {
	si.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// PasswordPolicy
// ---------------------------------------------------------------------------

func (pp *PasswordPolicy) GetConditions() []metav1.Condition {
	return pp.Status.Conditions
}

func (pp *PasswordPolicy) SetConditions(conditions []metav1.Condition) {
	pp.Status.Conditions = conditions
}

func (pp *PasswordPolicy) GetDeletionPolicy() DeletionPolicy {
	if pp.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return pp.Spec.DeletionPolicy
}

func (pp *PasswordPolicy) GetFullyQualifiedName() string {
	return pp.Status.FullyQualifiedName
}

func (pp *PasswordPolicy) GetProviderRef() ProviderReference {
	return pp.Spec.ProviderRef
}

func (pp *PasswordPolicy) GetSpecName() string {
	return pp.Spec.Name
}

func (pp *PasswordPolicy) GetUseRole() *string {
	return pp.Spec.UseRole
}

func (pp *PasswordPolicy) GetPaused() bool {
	return pp.Spec.Paused
}

func (pp *PasswordPolicy) GetManagementPolicies() ManagementPolicies {
	return pp.Spec.ManagementPolicies
}

func (pp *PasswordPolicy) SetCreateOrAlter(val *bool) {
	pp.Spec.ManagementPolicies.CreateOrAlter = val
}

func (pp *PasswordPolicy) GetObservedGeneration() int64 {
	return pp.Status.ObservedGeneration
}

func (pp *PasswordPolicy) SetObservedGeneration(val int64) {
	pp.Status.ObservedGeneration = val
}

func (pp *PasswordPolicy) GetLastAppliedSpecHash() string {
	return pp.Status.LastAppliedSpecHash
}

func (pp *PasswordPolicy) SetLastAppliedSpecHash(val string) {
	pp.Status.LastAppliedSpecHash = val
}

func (pp *PasswordPolicy) ValidateSpec() error {
	return pp.Spec.Validate()
}

func (pp *PasswordPolicy) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(pp.Spec)
}

func (pp *PasswordPolicy) GetOwner() string {
	if pp.Status.ShowOutput != nil {
		return pp.Status.ShowOutput.Owner
	}

	return ""
}

func (pp *PasswordPolicy) GetTrackedParametersList() []string {
	return pp.Status.TrackedParameters
}

func (pp *PasswordPolicy) SetTrackedParametersList(val []string) {
	pp.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// NetworkRule
// ---------------------------------------------------------------------------

func (nr *NetworkRule) GetConditions() []metav1.Condition {
	return nr.Status.Conditions
}

func (nr *NetworkRule) SetConditions(conditions []metav1.Condition) {
	nr.Status.Conditions = conditions
}

func (nr *NetworkRule) GetDeletionPolicy() DeletionPolicy {
	if nr.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return nr.Spec.DeletionPolicy
}

func (nr *NetworkRule) GetFullyQualifiedName() string {
	return nr.Status.FullyQualifiedName
}

func (nr *NetworkRule) GetProviderRef() ProviderReference {
	return nr.Spec.ProviderRef
}

func (nr *NetworkRule) GetSpecName() string {
	return nr.Spec.Name
}

func (nr *NetworkRule) GetUseRole() *string {
	return nr.Spec.UseRole
}

func (nr *NetworkRule) GetPaused() bool {
	return nr.Spec.Paused
}

func (nr *NetworkRule) GetManagementPolicies() ManagementPolicies {
	return nr.Spec.ManagementPolicies
}

func (nr *NetworkRule) SetCreateOrAlter(val *bool) {
	nr.Spec.ManagementPolicies.CreateOrAlter = val
}

func (nr *NetworkRule) GetObservedGeneration() int64 {
	return nr.Status.ObservedGeneration
}

func (nr *NetworkRule) SetObservedGeneration(val int64) {
	nr.Status.ObservedGeneration = val
}

func (nr *NetworkRule) GetLastAppliedSpecHash() string {
	return nr.Status.LastAppliedSpecHash
}

func (nr *NetworkRule) SetLastAppliedSpecHash(val string) {
	nr.Status.LastAppliedSpecHash = val
}

func (nr *NetworkRule) ValidateSpec() error {
	return nr.Spec.Validate()
}

func (nr *NetworkRule) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(nr.Spec)
}

func (nr *NetworkRule) GetOwner() string {
	if nr.Status.ShowOutput != nil {
		return nr.Status.ShowOutput.Owner
	}

	return ""
}

func (nr *NetworkRule) GetTrackedParametersList() []string {
	return nr.Status.TrackedParameters
}

func (nr *NetworkRule) SetTrackedParametersList(val []string) {
	nr.Status.TrackedParameters = val
}

// ---------------------------------------------------------------------------
// AccountRoleGrant
// ---------------------------------------------------------------------------

func (r *AccountRoleGrant) GetConditions() []metav1.Condition {
	return r.Status.Conditions
}

func (r *AccountRoleGrant) SetConditions(conditions []metav1.Condition) {
	r.Status.Conditions = conditions
}

func (r *AccountRoleGrant) GetDeletionPolicy() DeletionPolicy {
	if r.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return r.Spec.DeletionPolicy
}

func (r *AccountRoleGrant) GetFullyQualifiedName() string {
	return r.Status.FullyQualifiedName
}

func (r *AccountRoleGrant) GetProviderRef() ProviderReference {
	return r.Spec.ProviderRef
}

func (r *AccountRoleGrant) GetUseRole() *string {
	return r.Spec.UseRole
}

func (r *AccountRoleGrant) GetPaused() bool {
	return r.Spec.Paused
}

func (r *AccountRoleGrant) GetManagementPolicies() ManagementPolicies {
	return r.Spec.ManagementPolicies
}

func (r *AccountRoleGrant) SetCreateOrAlter(val *bool) {
	r.Spec.ManagementPolicies.CreateOrAlter = val
}

func (r *AccountRoleGrant) GetObservedGeneration() int64 {
	return r.Status.ObservedGeneration
}

func (r *AccountRoleGrant) SetObservedGeneration(val int64) {
	r.Status.ObservedGeneration = val
}

func (r *AccountRoleGrant) GetLastAppliedSpecHash() string {
	return r.Status.LastAppliedSpecHash
}

func (r *AccountRoleGrant) SetLastAppliedSpecHash(val string) {
	r.Status.LastAppliedSpecHash = val
}

func (r *AccountRoleGrant) ValidateSpec() error {
	return r.Spec.Validate()
}

func (r *AccountRoleGrant) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(r.Spec)
}

func (r *AccountRoleGrant) GetOwner() string {
	if r.Status.ShowOutput != nil {
		return r.Status.ShowOutput.GrantedBy
	}

	return ""
}

func (r *AccountRoleGrant) GetTrackedParametersList() []string { return nil }

func (r *AccountRoleGrant) SetTrackedParametersList(_ []string) {}

// ---------------------------------------------------------------------------
// DatabaseRoleGrant
// ---------------------------------------------------------------------------

func (r *DatabaseRoleGrant) GetConditions() []metav1.Condition {
	return r.Status.Conditions
}

func (r *DatabaseRoleGrant) SetConditions(conditions []metav1.Condition) {
	r.Status.Conditions = conditions
}

func (r *DatabaseRoleGrant) GetDeletionPolicy() DeletionPolicy {
	if r.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return r.Spec.DeletionPolicy
}

func (r *DatabaseRoleGrant) GetFullyQualifiedName() string {
	return r.Status.FullyQualifiedName
}

func (r *DatabaseRoleGrant) GetProviderRef() ProviderReference {
	return r.Spec.ProviderRef
}

func (r *DatabaseRoleGrant) GetUseRole() *string {
	return r.Spec.UseRole
}

func (r *DatabaseRoleGrant) GetPaused() bool {
	return r.Spec.Paused
}

func (r *DatabaseRoleGrant) GetManagementPolicies() ManagementPolicies {
	return r.Spec.ManagementPolicies
}

func (r *DatabaseRoleGrant) SetCreateOrAlter(val *bool) {
	r.Spec.ManagementPolicies.CreateOrAlter = val
}

func (r *DatabaseRoleGrant) GetObservedGeneration() int64 {
	return r.Status.ObservedGeneration
}

func (r *DatabaseRoleGrant) SetObservedGeneration(val int64) {
	r.Status.ObservedGeneration = val
}

func (r *DatabaseRoleGrant) GetLastAppliedSpecHash() string {
	return r.Status.LastAppliedSpecHash
}

func (r *DatabaseRoleGrant) SetLastAppliedSpecHash(val string) {
	r.Status.LastAppliedSpecHash = val
}

func (r *DatabaseRoleGrant) ValidateSpec() error {
	return r.Spec.Validate()
}

func (r *DatabaseRoleGrant) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(r.Spec)
}

func (r *DatabaseRoleGrant) GetOwner() string {
	if r.Status.ShowOutput != nil {
		return r.Status.ShowOutput.GrantedBy
	}

	return ""
}

func (r *DatabaseRoleGrant) GetTrackedParametersList() []string { return nil }

func (r *DatabaseRoleGrant) SetTrackedParametersList(_ []string) {}

// ---------------------------------------------------------------------------
// ShareGrant
// ---------------------------------------------------------------------------

func (r *ShareGrant) GetConditions() []metav1.Condition {
	return r.Status.Conditions
}

func (r *ShareGrant) SetConditions(conditions []metav1.Condition) {
	r.Status.Conditions = conditions
}

func (r *ShareGrant) GetDeletionPolicy() DeletionPolicy {
	if r.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return r.Spec.DeletionPolicy
}

func (r *ShareGrant) GetFullyQualifiedName() string {
	return r.Status.FullyQualifiedName
}

func (r *ShareGrant) GetProviderRef() ProviderReference {
	return r.Spec.ProviderRef
}

func (r *ShareGrant) GetUseRole() *string {
	return r.Spec.UseRole
}

func (r *ShareGrant) GetPaused() bool {
	return r.Spec.Paused
}

func (r *ShareGrant) GetManagementPolicies() ManagementPolicies {
	return r.Spec.ManagementPolicies
}

func (r *ShareGrant) SetCreateOrAlter(val *bool) {
	r.Spec.ManagementPolicies.CreateOrAlter = val
}

func (r *ShareGrant) GetObservedGeneration() int64 {
	return r.Status.ObservedGeneration
}

func (r *ShareGrant) SetObservedGeneration(val int64) {
	r.Status.ObservedGeneration = val
}

func (r *ShareGrant) GetLastAppliedSpecHash() string {
	return r.Status.LastAppliedSpecHash
}

func (r *ShareGrant) SetLastAppliedSpecHash(val string) {
	r.Status.LastAppliedSpecHash = val
}

func (r *ShareGrant) ValidateSpec() error {
	return r.Spec.Validate()
}

func (r *ShareGrant) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(r.Spec)
}

func (r *ShareGrant) GetOwner() string {
	if r.Status.ShowOutput != nil {
		return r.Status.ShowOutput.GrantedBy
	}

	return ""
}

func (r *ShareGrant) GetTrackedParametersList() []string { return nil }

func (r *ShareGrant) SetTrackedParametersList(_ []string) {}

// ---------------------------------------------------------------------------
// GrantOwnership
// ---------------------------------------------------------------------------

func (g *GrantOwnership) GetConditions() []metav1.Condition {
	return g.Status.Conditions
}

func (g *GrantOwnership) SetConditions(conditions []metav1.Condition) {
	g.Status.Conditions = conditions
}

func (g *GrantOwnership) GetDeletionPolicy() DeletionPolicy {
	if g.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return g.Spec.DeletionPolicy
}

func (g *GrantOwnership) GetFullyQualifiedName() string {
	return g.Status.FullyQualifiedName
}

func (g *GrantOwnership) GetProviderRef() ProviderReference {
	return g.Spec.ProviderRef
}

func (g *GrantOwnership) GetUseRole() *string {
	return g.Spec.UseRole
}

func (g *GrantOwnership) GetPaused() bool {
	return g.Spec.Paused
}

func (g *GrantOwnership) GetManagementPolicies() ManagementPolicies {
	return g.Spec.ManagementPolicies
}

func (g *GrantOwnership) SetCreateOrAlter(val *bool) {
	g.Spec.ManagementPolicies.CreateOrAlter = val
}

func (g *GrantOwnership) GetObservedGeneration() int64 {
	return g.Status.ObservedGeneration
}

func (g *GrantOwnership) SetObservedGeneration(val int64) {
	g.Status.ObservedGeneration = val
}

func (g *GrantOwnership) GetLastAppliedSpecHash() string {
	return g.Status.LastAppliedSpecHash
}

func (g *GrantOwnership) SetLastAppliedSpecHash(val string) {
	g.Status.LastAppliedSpecHash = val
}

func (g *GrantOwnership) ValidateSpec() error {
	return g.Spec.Validate()
}

func (g *GrantOwnership) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(g.Spec)
}

func (g *GrantOwnership) GetOwner() string {
	return ""
}

func (g *GrantOwnership) GetTrackedParametersList() []string { return nil }

func (g *GrantOwnership) SetTrackedParametersList(_ []string) {}

// ---------------------------------------------------------------------------
// AccountRoleAssignment
// ---------------------------------------------------------------------------

func (a *AccountRoleAssignment) GetConditions() []metav1.Condition {
	return a.Status.Conditions
}

func (a *AccountRoleAssignment) SetConditions(conditions []metav1.Condition) {
	a.Status.Conditions = conditions
}

func (a *AccountRoleAssignment) GetDeletionPolicy() DeletionPolicy {
	if a.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return a.Spec.DeletionPolicy
}

func (a *AccountRoleAssignment) GetFullyQualifiedName() string {
	return a.Status.FullyQualifiedName
}

func (a *AccountRoleAssignment) GetProviderRef() ProviderReference {
	return a.Spec.ProviderRef
}

func (a *AccountRoleAssignment) GetUseRole() *string {
	return a.Spec.UseRole
}

func (a *AccountRoleAssignment) GetPaused() bool {
	return a.Spec.Paused
}

func (a *AccountRoleAssignment) GetManagementPolicies() ManagementPolicies {
	return a.Spec.ManagementPolicies
}

func (a *AccountRoleAssignment) SetCreateOrAlter(val *bool) {
	a.Spec.ManagementPolicies.CreateOrAlter = val
}

func (a *AccountRoleAssignment) GetObservedGeneration() int64 {
	return a.Status.ObservedGeneration
}

func (a *AccountRoleAssignment) SetObservedGeneration(val int64) {
	a.Status.ObservedGeneration = val
}

func (a *AccountRoleAssignment) GetLastAppliedSpecHash() string {
	return a.Status.LastAppliedSpecHash
}

func (a *AccountRoleAssignment) SetLastAppliedSpecHash(val string) {
	a.Status.LastAppliedSpecHash = val
}

func (a *AccountRoleAssignment) ValidateSpec() error {
	return a.Spec.Validate()
}

func (a *AccountRoleAssignment) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(a.Spec)
}

func (a *AccountRoleAssignment) GetOwner() string {
	if a.Status.ShowOutput != nil {
		return a.Status.ShowOutput.GrantedBy
	}

	return ""
}

func (a *AccountRoleAssignment) GetTrackedParametersList() []string { return nil }

func (a *AccountRoleAssignment) SetTrackedParametersList(_ []string) {}

// ---------------------------------------------------------------------------
// DatabaseRoleAssignment
// ---------------------------------------------------------------------------

func (d *DatabaseRoleAssignment) GetConditions() []metav1.Condition {
	return d.Status.Conditions
}

func (d *DatabaseRoleAssignment) SetConditions(conditions []metav1.Condition) {
	d.Status.Conditions = conditions
}

func (d *DatabaseRoleAssignment) GetDeletionPolicy() DeletionPolicy {
	if d.Spec.DeletionPolicy == "" {
		return DeletionPolicyDelete
	}

	return d.Spec.DeletionPolicy
}

func (d *DatabaseRoleAssignment) GetFullyQualifiedName() string {
	return d.Status.FullyQualifiedName
}

func (d *DatabaseRoleAssignment) GetProviderRef() ProviderReference {
	return d.Spec.ProviderRef
}

func (d *DatabaseRoleAssignment) GetUseRole() *string {
	return d.Spec.UseRole
}

func (d *DatabaseRoleAssignment) GetPaused() bool {
	return d.Spec.Paused
}

func (d *DatabaseRoleAssignment) GetManagementPolicies() ManagementPolicies {
	return d.Spec.ManagementPolicies
}

func (d *DatabaseRoleAssignment) SetCreateOrAlter(val *bool) {
	d.Spec.ManagementPolicies.CreateOrAlter = val
}

func (d *DatabaseRoleAssignment) GetObservedGeneration() int64 {
	return d.Status.ObservedGeneration
}

func (d *DatabaseRoleAssignment) SetObservedGeneration(val int64) {
	d.Status.ObservedGeneration = val
}

func (d *DatabaseRoleAssignment) GetLastAppliedSpecHash() string {
	return d.Status.LastAppliedSpecHash
}

func (d *DatabaseRoleAssignment) SetLastAppliedSpecHash(val string) {
	d.Status.LastAppliedSpecHash = val
}

func (d *DatabaseRoleAssignment) ValidateSpec() error {
	return d.Spec.Validate()
}

func (d *DatabaseRoleAssignment) ComputeSpecHash() (string, error) {
	return ComputeSpecHash(d.Spec)
}

func (d *DatabaseRoleAssignment) GetOwner() string {
	if d.Status.ShowOutput != nil {
		return d.Status.ShowOutput.GrantedBy
	}

	return ""
}

func (d *DatabaseRoleAssignment) GetTrackedParametersList() []string { return nil }

func (d *DatabaseRoleAssignment) SetTrackedParametersList(_ []string) {}
