{{- if .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "snowplane.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snowplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "snowplane.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
{{- end }}
