{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "snowplane.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snowplane.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "snowplane.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: https
{{- end }}
